// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/directories": {
            "get": {
                "description": "Fetch directories via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directories"
                ],
                "summary": "List directories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Parent directory ID",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum results to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.DirectoryReply"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a directory via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directories"
                ],
                "summary": "Create directory",
                "parameters": [
                    {
                        "description": "Create directory request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateDirectoryBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DirectoryReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an existing directory via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directories"
                ],
                "summary": "Update directory",
                "parameters": [
                    {
                        "description": "Update directory request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PatchDirectoryBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DirectoryReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/directories/{id}": {
            "get": {
                "description": "Fetch directory via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directories"
                ],
                "summary": "Get directory by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Directory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DirectoryReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing directory via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directories"
                ],
                "summary": "Delete directory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Directory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.DirectoryReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notes": {
            "post": {
                "description": "Creates a new Note via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Post a Note",
                "parameters": [
                    {
                        "description": "Note ID",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PostNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.NoteReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an existing note via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a note",
                "parameters": [
                    {
                        "description": "Update Note Request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PatchNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.NoteReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notes/search": {
            "get": {
                "description": "Search notes via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get notes by search criteria",
                "parameters": [
                    {
                        "enum": [
                            "context",
                            "keyword",
                            "typo_tolerant",
                            "latest"
                        ],
                        "type": "string",
                        "description": "Search algorithm",
                        "name": "search_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum results to return",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.MinimalNote"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notes/{id}": {
            "get": {
                "description": "Fetch note via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get note by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Note ID (UUIDv7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.NoteReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an existing note via gRPC service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Note ID (UUIDv7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.NoteReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissions": {
            "get": {
                "description": "Fetch permissions via gRPC PermissionService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions"
                ],
                "summary": "Get permissions for an object",
                "parameters": [
                    {
                        "enum": [
                            "note",
                            "directory"
                        ],
                        "type": "string",
                        "description": "Object type",
                        "name": "object_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Object ID",
                        "name": "object_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionsReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Replace permissions via gRPC PermissionService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions"
                ],
                "summary": "Replace all permissions for an object",
                "parameters": [
                    {
                        "description": "Replace permissions request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ReplacePermissionsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionsReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create permission via gRPC PermissionService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions"
                ],
                "summary": "Create a permission relationship",
                "parameters": [
                    {
                        "description": "Create permission request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreatePermissionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionsReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete permission via gRPC PermissionService",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions"
                ],
                "summary": "Delete a permission relationship",
                "parameters": [
                    {
                        "description": "Delete permission request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.DeletePermissionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PermissionsReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CreateDirectoryBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Shared notes for engineering team"
                },
                "display_name": {
                    "type": "string",
                    "example": "Engineering"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/engineering.png"
                },
                "name": {
                    "type": "string",
                    "example": "engineering"
                },
                "parent_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                }
            }
        },
        "controllers.CreatePermissionBody": {
            "type": "object",
            "required": [
                "object_id",
                "object_type",
                "relationship"
            ],
            "properties": {
                "object_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "note",
                        "directory"
                    ],
                    "example": "note"
                },
                "relationship": {
                    "$ref": "#/definitions/controllers.PermissionRelationshipRequest"
                }
            }
        },
        "controllers.DeletePermissionBody": {
            "type": "object",
            "required": [
                "object_id",
                "object_type",
                "relationship"
            ],
            "properties": {
                "object_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "note",
                        "directory"
                    ],
                    "example": "note"
                },
                "relationship": {
                    "$ref": "#/definitions/controllers.PermissionRelationshipRequest"
                }
            }
        },
        "controllers.DirectoryReply": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PermissionRelationshipReply"
                    }
                }
            }
        },
        "controllers.MinimalNote": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PermissionRelationshipReply"
                    }
                },
                "stripped_content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "ISO 8601 format",
                    "type": "string"
                }
            }
        },
        "controllers.NoteReply": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PermissionRelationshipReply"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controllers.PatchDirectoryBody": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Shared notes for engineering team"
                },
                "display_name": {
                    "type": "string",
                    "example": "Engineering"
                },
                "id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/engineering.png"
                },
                "name": {
                    "type": "string",
                    "example": "engineering"
                },
                "parent_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                }
            }
        },
        "controllers.PatchNoteRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "This is the updated content of my note."
                },
                "id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "title": {
                    "type": "string",
                    "example": "Updated Note Title"
                }
            }
        },
        "controllers.PermissionRelationshipReply": {
            "type": "object",
            "properties": {
                "relation": {
                    "type": "string"
                },
                "resource": {
                    "$ref": "#/definitions/controllers.PermissionResourceReply"
                },
                "subject": {
                    "$ref": "#/definitions/controllers.PermissionSubjectReply"
                }
            }
        },
        "controllers.PermissionRelationshipRequest": {
            "type": "object",
            "required": [
                "relation"
            ],
            "properties": {
                "relation": {
                    "type": "string",
                    "enum": [
                        "owner",
                        "admin",
                        "writer",
                        "reader",
                        "parent",
                        "parent_directory"
                    ],
                    "example": "reader"
                },
                "resource": {
                    "$ref": "#/definitions/controllers.PermissionResourceRequest"
                },
                "subject": {
                    "$ref": "#/definitions/controllers.PermissionSubjectRequest"
                }
            }
        },
        "controllers.PermissionResourceReply": {
            "type": "object",
            "properties": {
                "object_id": {
                    "type": "string"
                },
                "object_type": {
                    "type": "string"
                }
            }
        },
        "controllers.PermissionResourceRequest": {
            "type": "object",
            "required": [
                "object_id",
                "object_type"
            ],
            "properties": {
                "object_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "note",
                        "directory"
                    ],
                    "example": "note"
                }
            }
        },
        "controllers.PermissionSubjectReply": {
            "type": "object",
            "properties": {
                "object_id": {
                    "type": "string"
                },
                "object_type": {
                    "type": "string"
                }
            }
        },
        "controllers.PermissionSubjectRequest": {
            "type": "object",
            "required": [
                "object_id",
                "object_type"
            ],
            "properties": {
                "object_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "user",
                        "directory"
                    ],
                    "example": "user"
                }
            }
        },
        "controllers.PermissionsReply": {
            "type": "object",
            "properties": {
                "object_id": {
                    "type": "string"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "PERMISSION_OBJECT_TYPE_UNSPECIFIED",
                        "PERMISSION_OBJECT_TYPE_NOTE",
                        "PERMISSION_OBJECT_TYPE_DIRECTORY"
                    ]
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PermissionRelationshipReply"
                    }
                }
            }
        },
        "controllers.PostNoteRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "This is the content of my note."
                },
                "title": {
                    "type": "string",
                    "example": "My Note Title"
                }
            }
        },
        "controllers.ReplacePermissionsBody": {
            "type": "object",
            "required": [
                "object_id",
                "object_type",
                "relationships"
            ],
            "properties": {
                "object_id": {
                    "type": "string",
                    "example": "0195f8f4-1167-7f89-b5ec-b40a8f08f4cb"
                },
                "object_type": {
                    "type": "string",
                    "enum": [
                        "note",
                        "directory"
                    ],
                    "example": "note"
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PermissionRelationshipRequest"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "discord_auth",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "GoToHell Gin REST API",
	Description:      "Provides all methods to persist data for GoToHell",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
