definitions:
  controllers.MinimalNote:
    properties:
      author_id:
        type: string
      id:
        type: string
      stripped_content:
        type: string
      title:
        type: string
      updated_at:
        description: ISO 8601 format
        type: string
    type: object
  controllers.NoteReply:
    properties:
      author_id:
        type: string
      content:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  controllers.PatchNoteRequest:
    properties:
      content:
        example: This is the updated content of my note.
        type: string
      id:
        example: 0195f8f4-1167-7f89-b5ec-b40a8f08f4cb
        type: string
      title:
        example: Updated Note Title
        type: string
    required:
    - id
    type: object
  controllers.PostNoteRequest:
    properties:
      content:
        example: This is the content of my note.
        type: string
      title:
        example: My Note Title
        type: string
    required:
    - content
    - title
    type: object
info:
  contact: {}
  description: Provides all methods to persist data for GoToHell
  title: GoToHell Gin REST API
paths:
  /notes:
    patch:
      consumes:
      - application/json
      description: Updates an existing note via gRPC service
      parameters:
      - description: Update Note Request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.PatchNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a note
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates a new Note via gRPC service
      parameters:
      - description: Note ID
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.PostNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post a Note
      tags:
      - users
  /notes/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an existing note via gRPC service
      parameters:
      - description: Note ID (UUIDv7)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a note
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Fetch note via gRPC service
      parameters:
      - description: Note ID (UUIDv7)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get note by ID
      tags:
      - users
  /notes/search:
    get:
      consumes:
      - application/json
      description: Search notes via gRPC service
      parameters:
      - description: Search algorithm
        enum:
        - context
        - keyword
        - typo_tolerant
        - latest
        in: query
        name: search_type
        required: true
        type: string
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      - description: Maximum results to return
        in: query
        name: limit
        required: true
        type: integer
      - description: Pagination offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.MinimalNote'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get notes by search criteria
      tags:
      - users
securityDefinitions:
  CookieAuth:
    in: cookie
    name: discord_auth
    type: apiKey
swagger: "2.0"
