// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: src/proto/activity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityStatisticsService_GetActivityHistory_FullMethodName  = "/proto.ActivityStatisticsService/GetActivityHistory"
	ActivityStatisticsService_GetMostUsedActivity_FullMethodName = "/proto.ActivityStatisticsService/GetMostUsedActivity"
)

// ActivityStatisticsServiceClient is the client API for ActivityStatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityStatisticsServiceClient interface {
	// Streams the activity log for everything the actor can view.
	GetActivityHistory(ctx context.Context, in *GetActivityHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Activity], error)
	// Streams aggregate note scores for everything the actor can view.
	GetMostUsedActivity(ctx context.Context, in *GetMostUsedActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivityScore], error)
}

type activityStatisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityStatisticsServiceClient(cc grpc.ClientConnInterface) ActivityStatisticsServiceClient {
	return &activityStatisticsServiceClient{cc}
}

func (c *activityStatisticsServiceClient) GetActivityHistory(ctx context.Context, in *GetActivityHistoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Activity], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActivityStatisticsService_ServiceDesc.Streams[0], ActivityStatisticsService_GetActivityHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetActivityHistoryRequest, Activity]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivityStatisticsService_GetActivityHistoryClient = grpc.ServerStreamingClient[Activity]

func (c *activityStatisticsServiceClient) GetMostUsedActivity(ctx context.Context, in *GetMostUsedActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActivityScore], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActivityStatisticsService_ServiceDesc.Streams[1], ActivityStatisticsService_GetMostUsedActivity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMostUsedActivityRequest, ActivityScore]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivityStatisticsService_GetMostUsedActivityClient = grpc.ServerStreamingClient[ActivityScore]

// ActivityStatisticsServiceServer is the server API for ActivityStatisticsService service.
// All implementations must embed UnimplementedActivityStatisticsServiceServer
// for forward compatibility.
type ActivityStatisticsServiceServer interface {
	// Streams the activity log for everything the actor can view.
	GetActivityHistory(*GetActivityHistoryRequest, grpc.ServerStreamingServer[Activity]) error
	// Streams aggregate note scores for everything the actor can view.
	GetMostUsedActivity(*GetMostUsedActivityRequest, grpc.ServerStreamingServer[ActivityScore]) error
	mustEmbedUnimplementedActivityStatisticsServiceServer()
}

// UnimplementedActivityStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityStatisticsServiceServer struct{}

func (UnimplementedActivityStatisticsServiceServer) GetActivityHistory(*GetActivityHistoryRequest, grpc.ServerStreamingServer[Activity]) error {
	return status.Error(codes.Unimplemented, "method GetActivityHistory not implemented")
}
func (UnimplementedActivityStatisticsServiceServer) GetMostUsedActivity(*GetMostUsedActivityRequest, grpc.ServerStreamingServer[ActivityScore]) error {
	return status.Error(codes.Unimplemented, "method GetMostUsedActivity not implemented")
}
func (UnimplementedActivityStatisticsServiceServer) mustEmbedUnimplementedActivityStatisticsServiceServer() {
}
func (UnimplementedActivityStatisticsServiceServer) testEmbeddedByValue() {}

// UnsafeActivityStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityStatisticsServiceServer will
// result in compilation errors.
type UnsafeActivityStatisticsServiceServer interface {
	mustEmbedUnimplementedActivityStatisticsServiceServer()
}

func RegisterActivityStatisticsServiceServer(s grpc.ServiceRegistrar, srv ActivityStatisticsServiceServer) {
	// If the following call panics, it indicates UnimplementedActivityStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityStatisticsService_ServiceDesc, srv)
}

func _ActivityStatisticsService_GetActivityHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetActivityHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActivityStatisticsServiceServer).GetActivityHistory(m, &grpc.GenericServerStream[GetActivityHistoryRequest, Activity]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivityStatisticsService_GetActivityHistoryServer = grpc.ServerStreamingServer[Activity]

func _ActivityStatisticsService_GetMostUsedActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMostUsedActivityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActivityStatisticsServiceServer).GetMostUsedActivity(m, &grpc.GenericServerStream[GetMostUsedActivityRequest, ActivityScore]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivityStatisticsService_GetMostUsedActivityServer = grpc.ServerStreamingServer[ActivityScore]

// ActivityStatisticsService_ServiceDesc is the grpc.ServiceDesc for ActivityStatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityStatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ActivityStatisticsService",
	HandlerType: (*ActivityStatisticsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetActivityHistory",
			Handler:       _ActivityStatisticsService_GetActivityHistory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMostUsedActivity",
			Handler:       _ActivityStatisticsService_GetMostUsedActivity_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/activity.proto",
}
