// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: src/proto/attachments.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachmentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Filepath      string                 `protobuf:"bytes,3,opt,name=filepath,proto3" json:"filepath,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Sha256        string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentMetadata) Reset() {
	*x = AttachmentMetadata{}
	mi := &file_src_proto_attachments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentMetadata) ProtoMessage() {}

func (x *AttachmentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentMetadata.ProtoReflect.Descriptor instead.
func (*AttachmentMetadata) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{0}
}

func (x *AttachmentMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttachmentMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AttachmentMetadata) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *AttachmentMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AttachmentMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttachmentMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AttachmentMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AttachmentMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *AttachmentMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_src_proto_attachments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetMetadata() *AttachmentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Attachment) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PostAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAttachmentRequest) Reset() {
	*x = PostAttachmentRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAttachmentRequest) ProtoMessage() {}

func (x *PostAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAttachmentRequest.ProtoReflect.Descriptor instead.
func (*PostAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{2}
}

func (x *PostAttachmentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PostAttachmentRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *PostAttachmentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PostAttachmentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PostAttachmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PostAttachmentLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentKey string                 `protobuf:"bytes,1,opt,name=attachment_key,json=attachmentKey,proto3" json:"attachment_key,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAttachmentLinkRequest) Reset() {
	*x = PostAttachmentLinkRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAttachmentLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAttachmentLinkRequest) ProtoMessage() {}

func (x *PostAttachmentLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAttachmentLinkRequest.ProtoReflect.Descriptor instead.
func (*PostAttachmentLinkRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{3}
}

func (x *PostAttachmentLinkRequest) GetAttachmentKey() string {
	if x != nil {
		return x.AttachmentKey
	}
	return ""
}

func (x *PostAttachmentLinkRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *PostAttachmentLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAttachmentLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentKey string                 `protobuf:"bytes,1,opt,name=attachment_key,json=attachmentKey,proto3" json:"attachment_key,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentLinkRequest) Reset() {
	*x = DeleteAttachmentLinkRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentLinkRequest) ProtoMessage() {}

func (x *DeleteAttachmentLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentLinkRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAttachmentLinkRequest) GetAttachmentKey() string {
	if x != nil {
		return x.AttachmentKey
	}
	return ""
}

func (x *DeleteAttachmentLinkRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *DeleteAttachmentLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttachmentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetAttachmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAttachmentMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentMetadataRequest) Reset() {
	*x = GetAttachmentMetadataRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentMetadataRequest) ProtoMessage() {}

func (x *GetAttachmentMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentMetadataRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttachmentMetadataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetAttachmentMetadataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentRequest) Reset() {
	*x = DeleteAttachmentRequest{}
	mi := &file_src_proto_attachments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentRequest) ProtoMessage() {}

func (x *DeleteAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAttachmentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteAttachmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentResponse) Reset() {
	*x = DeleteAttachmentResponse{}
	mi := &file_src_proto_attachments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentResponse) ProtoMessage() {}

func (x *DeleteAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_attachments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_attachments_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAttachmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_src_proto_attachments_proto protoreflect.FileDescriptor

const file_src_proto_attachments_proto_rawDesc = "" +
	"\n" +
	"\x1bsrc/proto/attachments.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa3\x02\n" +
	"\x12AttachmentMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilepath\x18\x03 \x01(\tR\bfilepath\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\"]\n" +
	"\n" +
	"Attachment\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.proto.AttachmentMetadataR\bmetadata\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xa5\x01\n" +
	"\x15PostAttachmentRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"t\n" +
	"\x19PostAttachmentLinkRequest\x12%\n" +
	"\x0eattachment_key\x18\x01 \x01(\tR\rattachmentKey\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"v\n" +
	"\x1bDeleteAttachmentLinkRequest\x12%\n" +
	"\x0eattachment_key\x18\x01 \x01(\tR\rattachmentKey\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"A\n" +
	"\x14GetAttachmentRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x1cGetAttachmentMetadataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x17DeleteAttachmentRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x18DeleteAttachmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbb\x04\n" +
	"\x11AttachmentService\x12A\n" +
	"\x0ePostAttachment\x12\x1c.proto.PostAttachmentRequest\x1a\x11.proto.Attachment\x12?\n" +
	"\rGetAttachment\x12\x1b.proto.GetAttachmentRequest\x1a\x11.proto.Attachment\x12W\n" +
	"\x15GetAttachmentMetadata\x12#.proto.GetAttachmentMetadataRequest\x1a\x19.proto.AttachmentMetadata\x12S\n" +
	"\x10DeleteAttachment\x12\x1e.proto.DeleteAttachmentRequest\x1a\x1f.proto.DeleteAttachmentResponse\x12P\n" +
	"\x18UpdateAttachmentMetadata\x12\x19.proto.AttachmentMetadata\x1a\x19.proto.AttachmentMetadata\x12N\n" +
	"\x12PostAttachmentLink\x12 .proto.PostAttachmentLinkRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x14DeleteAttachmentLink\x12\".proto.DeleteAttachmentLinkRequest\x1a\x16.google.protobuf.EmptyB1Z/github.com/KuramaSyu/WerSu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_attachments_proto_rawDescOnce sync.Once
	file_src_proto_attachments_proto_rawDescData []byte
)

func file_src_proto_attachments_proto_rawDescGZIP() []byte {
	file_src_proto_attachments_proto_rawDescOnce.Do(func() {
		file_src_proto_attachments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_attachments_proto_rawDesc), len(file_src_proto_attachments_proto_rawDesc)))
	})
	return file_src_proto_attachments_proto_rawDescData
}

var file_src_proto_attachments_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_proto_attachments_proto_goTypes = []any{
	(*AttachmentMetadata)(nil),           // 0: proto.AttachmentMetadata
	(*Attachment)(nil),                   // 1: proto.Attachment
	(*PostAttachmentRequest)(nil),        // 2: proto.PostAttachmentRequest
	(*PostAttachmentLinkRequest)(nil),    // 3: proto.PostAttachmentLinkRequest
	(*DeleteAttachmentLinkRequest)(nil),  // 4: proto.DeleteAttachmentLinkRequest
	(*GetAttachmentRequest)(nil),         // 5: proto.GetAttachmentRequest
	(*GetAttachmentMetadataRequest)(nil), // 6: proto.GetAttachmentMetadataRequest
	(*DeleteAttachmentRequest)(nil),      // 7: proto.DeleteAttachmentRequest
	(*DeleteAttachmentResponse)(nil),     // 8: proto.DeleteAttachmentResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
}
var file_src_proto_attachments_proto_depIdxs = []int32{
	9,  // 0: proto.AttachmentMetadata.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: proto.AttachmentMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: proto.Attachment.metadata:type_name -> proto.AttachmentMetadata
	2,  // 3: proto.AttachmentService.PostAttachment:input_type -> proto.PostAttachmentRequest
	5,  // 4: proto.AttachmentService.GetAttachment:input_type -> proto.GetAttachmentRequest
	6,  // 5: proto.AttachmentService.GetAttachmentMetadata:input_type -> proto.GetAttachmentMetadataRequest
	7,  // 6: proto.AttachmentService.DeleteAttachment:input_type -> proto.DeleteAttachmentRequest
	0,  // 7: proto.AttachmentService.UpdateAttachmentMetadata:input_type -> proto.AttachmentMetadata
	3,  // 8: proto.AttachmentService.PostAttachmentLink:input_type -> proto.PostAttachmentLinkRequest
	4,  // 9: proto.AttachmentService.DeleteAttachmentLink:input_type -> proto.DeleteAttachmentLinkRequest
	1,  // 10: proto.AttachmentService.PostAttachment:output_type -> proto.Attachment
	1,  // 11: proto.AttachmentService.GetAttachment:output_type -> proto.Attachment
	0,  // 12: proto.AttachmentService.GetAttachmentMetadata:output_type -> proto.AttachmentMetadata
	8,  // 13: proto.AttachmentService.DeleteAttachment:output_type -> proto.DeleteAttachmentResponse
	0,  // 14: proto.AttachmentService.UpdateAttachmentMetadata:output_type -> proto.AttachmentMetadata
	10, // 15: proto.AttachmentService.PostAttachmentLink:output_type -> google.protobuf.Empty
	10, // 16: proto.AttachmentService.DeleteAttachmentLink:output_type -> google.protobuf.Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_src_proto_attachments_proto_init() }
func file_src_proto_attachments_proto_init() {
	if File_src_proto_attachments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_attachments_proto_rawDesc), len(file_src_proto_attachments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_attachments_proto_goTypes,
		DependencyIndexes: file_src_proto_attachments_proto_depIdxs,
		MessageInfos:      file_src_proto_attachments_proto_msgTypes,
	}.Build()
	File_src_proto_attachments_proto = out.File
	file_src_proto_attachments_proto_goTypes = nil
	file_src_proto_attachments_proto_depIdxs = nil
}
