// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: src/proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GetUserAuth_FullMethodName              = "/proto.AuthService/GetUserAuth"
	AuthService_CreateUserAuth_FullMethodName           = "/proto.AuthService/CreateUserAuth"
	AuthService_UpdateUserAuth_FullMethodName           = "/proto.AuthService/UpdateUserAuth"
	AuthService_FindCredentialByProvider_FullMethodName = "/proto.AuthService/FindCredentialByProvider"
	AuthService_FindPasskey_FullMethodName              = "/proto.AuthService/FindPasskey"
	AuthService_ListPasskeys_FullMethodName             = "/proto.AuthService/ListPasskeys"
	AuthService_UpdatePasskeyCounter_FullMethodName     = "/proto.AuthService/UpdatePasskeyCounter"
	AuthService_RegisterPasskey_FullMethodName          = "/proto.AuthService/RegisterPasskey"
	AuthService_RevokePasskey_FullMethodName            = "/proto.AuthService/RevokePasskey"
	AuthService_LinkCredential_FullMethodName           = "/proto.AuthService/LinkCredential"
	AuthService_UnlinkCredential_FullMethodName         = "/proto.AuthService/UnlinkCredential"
	AuthService_ListLinkedCredentials_FullMethodName    = "/proto.AuthService/ListLinkedCredentials"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// user lookup
	GetUserAuth(ctx context.Context, in *GetUserAuthRequest, opts ...grpc.CallOption) (*GetUserAuthResponse, error)
	CreateUserAuth(ctx context.Context, in *CreateUserAuthRequest, opts ...grpc.CallOption) (*CreateUserAuthResponse, error)
	UpdateUserAuth(ctx context.Context, in *UpdateUserAuthRequest, opts ...grpc.CallOption) (*UpdateUserAuthResponse, error)
	// credential lookup
	FindCredentialByProvider(ctx context.Context, in *FindCredentialByProviderRequest, opts ...grpc.CallOption) (*FindCredentialByProviderResponse, error)
	FindPasskey(ctx context.Context, in *FindPasskeyRequest, opts ...grpc.CallOption) (*FindPasskeyResponse, error)
	ListPasskeys(ctx context.Context, in *ListPasskeysRequest, opts ...grpc.CallOption) (*ListPasskeysResponse, error)
	UpdatePasskeyCounter(ctx context.Context, in *UpdatePasskeyCounterRequest, opts ...grpc.CallOption) (*UpdatePasskeyCounterResponse, error)
	RegisterPasskey(ctx context.Context, in *RegisterPasskeyRequest, opts ...grpc.CallOption) (*RegisterPasskeyResponse, error)
	RevokePasskey(ctx context.Context, in *RevokePasskeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// account linking
	LinkCredential(ctx context.Context, in *LinkCredentialRequest, opts ...grpc.CallOption) (*LinkCredentialResponse, error)
	UnlinkCredential(ctx context.Context, in *UnlinkCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListLinkedCredentials(ctx context.Context, in *ListLinkedCredentialsRequest, opts ...grpc.CallOption) (*ListLinkedCredentialsResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetUserAuth(ctx context.Context, in *GetUserAuthRequest, opts ...grpc.CallOption) (*GetUserAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAuthResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateUserAuth(ctx context.Context, in *CreateUserAuthRequest, opts ...grpc.CallOption) (*CreateUserAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserAuthResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateUserAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateUserAuth(ctx context.Context, in *UpdateUserAuthRequest, opts ...grpc.CallOption) (*UpdateUserAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserAuthResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdateUserAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindCredentialByProvider(ctx context.Context, in *FindCredentialByProviderRequest, opts ...grpc.CallOption) (*FindCredentialByProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindCredentialByProviderResponse)
	err := c.cc.Invoke(ctx, AuthService_FindCredentialByProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) FindPasskey(ctx context.Context, in *FindPasskeyRequest, opts ...grpc.CallOption) (*FindPasskeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPasskeyResponse)
	err := c.cc.Invoke(ctx, AuthService_FindPasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListPasskeys(ctx context.Context, in *ListPasskeysRequest, opts ...grpc.CallOption) (*ListPasskeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPasskeysResponse)
	err := c.cc.Invoke(ctx, AuthService_ListPasskeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdatePasskeyCounter(ctx context.Context, in *UpdatePasskeyCounterRequest, opts ...grpc.CallOption) (*UpdatePasskeyCounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasskeyCounterResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdatePasskeyCounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterPasskey(ctx context.Context, in *RegisterPasskeyRequest, opts ...grpc.CallOption) (*RegisterPasskeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPasskeyResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterPasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokePasskey(ctx context.Context, in *RevokePasskeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_RevokePasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LinkCredential(ctx context.Context, in *LinkCredentialRequest, opts ...grpc.CallOption) (*LinkCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkCredentialResponse)
	err := c.cc.Invoke(ctx, AuthService_LinkCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UnlinkCredential(ctx context.Context, in *UnlinkCredentialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthService_UnlinkCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListLinkedCredentials(ctx context.Context, in *ListLinkedCredentialsRequest, opts ...grpc.CallOption) (*ListLinkedCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinkedCredentialsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListLinkedCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// user lookup
	GetUserAuth(context.Context, *GetUserAuthRequest) (*GetUserAuthResponse, error)
	CreateUserAuth(context.Context, *CreateUserAuthRequest) (*CreateUserAuthResponse, error)
	UpdateUserAuth(context.Context, *UpdateUserAuthRequest) (*UpdateUserAuthResponse, error)
	// credential lookup
	FindCredentialByProvider(context.Context, *FindCredentialByProviderRequest) (*FindCredentialByProviderResponse, error)
	FindPasskey(context.Context, *FindPasskeyRequest) (*FindPasskeyResponse, error)
	ListPasskeys(context.Context, *ListPasskeysRequest) (*ListPasskeysResponse, error)
	UpdatePasskeyCounter(context.Context, *UpdatePasskeyCounterRequest) (*UpdatePasskeyCounterResponse, error)
	RegisterPasskey(context.Context, *RegisterPasskeyRequest) (*RegisterPasskeyResponse, error)
	RevokePasskey(context.Context, *RevokePasskeyRequest) (*emptypb.Empty, error)
	// account linking
	LinkCredential(context.Context, *LinkCredentialRequest) (*LinkCredentialResponse, error)
	UnlinkCredential(context.Context, *UnlinkCredentialRequest) (*emptypb.Empty, error)
	ListLinkedCredentials(context.Context, *ListLinkedCredentialsRequest) (*ListLinkedCredentialsResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GetUserAuth(context.Context, *GetUserAuthRequest) (*GetUserAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAuth not implemented")
}
func (UnimplementedAuthServiceServer) CreateUserAuth(context.Context, *CreateUserAuthRequest) (*CreateUserAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserAuth not implemented")
}
func (UnimplementedAuthServiceServer) UpdateUserAuth(context.Context, *UpdateUserAuthRequest) (*UpdateUserAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserAuth not implemented")
}
func (UnimplementedAuthServiceServer) FindCredentialByProvider(context.Context, *FindCredentialByProviderRequest) (*FindCredentialByProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindCredentialByProvider not implemented")
}
func (UnimplementedAuthServiceServer) FindPasskey(context.Context, *FindPasskeyRequest) (*FindPasskeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPasskey not implemented")
}
func (UnimplementedAuthServiceServer) ListPasskeys(context.Context, *ListPasskeysRequest) (*ListPasskeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPasskeys not implemented")
}
func (UnimplementedAuthServiceServer) UpdatePasskeyCounter(context.Context, *UpdatePasskeyCounterRequest) (*UpdatePasskeyCounterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePasskeyCounter not implemented")
}
func (UnimplementedAuthServiceServer) RegisterPasskey(context.Context, *RegisterPasskeyRequest) (*RegisterPasskeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPasskey not implemented")
}
func (UnimplementedAuthServiceServer) RevokePasskey(context.Context, *RevokePasskeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokePasskey not implemented")
}
func (UnimplementedAuthServiceServer) LinkCredential(context.Context, *LinkCredentialRequest) (*LinkCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkCredential not implemented")
}
func (UnimplementedAuthServiceServer) UnlinkCredential(context.Context, *UnlinkCredentialRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkCredential not implemented")
}
func (UnimplementedAuthServiceServer) ListLinkedCredentials(context.Context, *ListLinkedCredentialsRequest) (*ListLinkedCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinkedCredentials not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GetUserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserAuth(ctx, req.(*GetUserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateUserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateUserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateUserAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateUserAuth(ctx, req.(*CreateUserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateUserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateUserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateUserAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateUserAuth(ctx, req.(*UpdateUserAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindCredentialByProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCredentialByProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindCredentialByProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_FindCredentialByProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindCredentialByProvider(ctx, req.(*FindCredentialByProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_FindPasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).FindPasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_FindPasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).FindPasskey(ctx, req.(*FindPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListPasskeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPasskeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListPasskeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListPasskeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListPasskeys(ctx, req.(*ListPasskeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdatePasskeyCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasskeyCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdatePasskeyCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdatePasskeyCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdatePasskeyCounter(ctx, req.(*UpdatePasskeyCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterPasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterPasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterPasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterPasskey(ctx, req.(*RegisterPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokePasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokePasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokePasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokePasskey(ctx, req.(*RevokePasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LinkCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LinkCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LinkCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LinkCredential(ctx, req.(*LinkCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UnlinkCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UnlinkCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UnlinkCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UnlinkCredential(ctx, req.(*UnlinkCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListLinkedCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinkedCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListLinkedCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListLinkedCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListLinkedCredentials(ctx, req.(*ListLinkedCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAuth",
			Handler:    _AuthService_GetUserAuth_Handler,
		},
		{
			MethodName: "CreateUserAuth",
			Handler:    _AuthService_CreateUserAuth_Handler,
		},
		{
			MethodName: "UpdateUserAuth",
			Handler:    _AuthService_UpdateUserAuth_Handler,
		},
		{
			MethodName: "FindCredentialByProvider",
			Handler:    _AuthService_FindCredentialByProvider_Handler,
		},
		{
			MethodName: "FindPasskey",
			Handler:    _AuthService_FindPasskey_Handler,
		},
		{
			MethodName: "ListPasskeys",
			Handler:    _AuthService_ListPasskeys_Handler,
		},
		{
			MethodName: "UpdatePasskeyCounter",
			Handler:    _AuthService_UpdatePasskeyCounter_Handler,
		},
		{
			MethodName: "RegisterPasskey",
			Handler:    _AuthService_RegisterPasskey_Handler,
		},
		{
			MethodName: "RevokePasskey",
			Handler:    _AuthService_RevokePasskey_Handler,
		},
		{
			MethodName: "LinkCredential",
			Handler:    _AuthService_LinkCredential_Handler,
		},
		{
			MethodName: "UnlinkCredential",
			Handler:    _AuthService_UnlinkCredential_Handler,
		},
		{
			MethodName: "ListLinkedCredentials",
			Handler:    _AuthService_ListLinkedCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/auth.proto",
}
