// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: src/proto/note.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteService_GetNote_FullMethodName     = "/proto.NoteService/GetNote"
	NoteService_PostNote_FullMethodName    = "/proto.NoteService/PostNote"
	NoteService_PatchNote_FullMethodName   = "/proto.NoteService/PatchNote"
	NoteService_DeleteNote_FullMethodName  = "/proto.NoteService/DeleteNote"
	NoteService_SearchNotes_FullMethodName = "/proto.NoteService/SearchNotes"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Note Service
type NoteServiceClient interface {
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*Note, error)
	PostNote(ctx context.Context, in *PostNoteRequest, opts ...grpc.CallOption) (*Note, error)
	PatchNote(ctx context.Context, in *AlterNoteRequest, opts ...grpc.CallOption) (*Note, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*Note, error)
	SearchNotes(ctx context.Context, in *GetSearchNotesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MinimalNote], error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteService_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) PostNote(ctx context.Context, in *PostNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteService_PostNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) PatchNote(ctx context.Context, in *AlterNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteService_PatchNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteService_DeleteNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) SearchNotes(ctx context.Context, in *GetSearchNotesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MinimalNote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteService_ServiceDesc.Streams[0], NoteService_SearchNotes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSearchNotesRequest, MinimalNote]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteService_SearchNotesClient = grpc.ServerStreamingClient[MinimalNote]

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility.
//
// Note Service
type NoteServiceServer interface {
	GetNote(context.Context, *GetNoteRequest) (*Note, error)
	PostNote(context.Context, *PostNoteRequest) (*Note, error)
	PatchNote(context.Context, *AlterNoteRequest) (*Note, error)
	DeleteNote(context.Context, *DeleteNoteRequest) (*Note, error)
	SearchNotes(*GetSearchNotesRequest, grpc.ServerStreamingServer[MinimalNote]) error
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteServiceServer struct{}

func (UnimplementedNoteServiceServer) GetNote(context.Context, *GetNoteRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteServiceServer) PostNote(context.Context, *PostNoteRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method PostNote not implemented")
}
func (UnimplementedNoteServiceServer) PatchNote(context.Context, *AlterNoteRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchNote not implemented")
}
func (UnimplementedNoteServiceServer) DeleteNote(context.Context, *DeleteNoteRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedNoteServiceServer) SearchNotes(*GetSearchNotesRequest, grpc.ServerStreamingServer[MinimalNote]) error {
	return status.Error(codes.Unimplemented, "method SearchNotes not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}
func (UnimplementedNoteServiceServer) testEmbeddedByValue()                     {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	// If the following call panics, it indicates UnimplementedNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_PostNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).PostNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_PostNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).PostNote(ctx, req.(*PostNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_PatchNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlterNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).PatchNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_PatchNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).PatchNote(ctx, req.(*AlterNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_SearchNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSearchNotesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteServiceServer).SearchNotes(m, &grpc.GenericServerStream[GetSearchNotesRequest, MinimalNote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteService_SearchNotesServer = grpc.ServerStreamingServer[MinimalNote]

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteService_GetNote_Handler,
		},
		{
			MethodName: "PostNote",
			Handler:    _NoteService_PostNote_Handler,
		},
		{
			MethodName: "PatchNote",
			Handler:    _NoteService_PatchNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _NoteService_DeleteNote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchNotes",
			Handler:       _NoteService_SearchNotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/note.proto",
}

const (
	DirectoryService_GetDirectory_FullMethodName    = "/proto.DirectoryService/GetDirectory"
	DirectoryService_GetDirectories_FullMethodName  = "/proto.DirectoryService/GetDirectories"
	DirectoryService_CreateDirectory_FullMethodName = "/proto.DirectoryService/CreateDirectory"
	DirectoryService_PatchDirectory_FullMethodName  = "/proto.DirectoryService/PatchDirectory"
	DirectoryService_DeleteDirectory_FullMethodName = "/proto.DirectoryService/DeleteDirectory"
)

// DirectoryServiceClient is the client API for DirectoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirectoryServiceClient interface {
	GetDirectory(ctx context.Context, in *GetDirectoryRequest, opts ...grpc.CallOption) (*Directory, error)
	GetDirectories(ctx context.Context, in *GetDirectoriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directory], error)
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*Directory, error)
	PatchDirectory(ctx context.Context, in *AlterDirectoryRequest, opts ...grpc.CallOption) (*Directory, error)
	DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*Directory, error)
}

type directoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryServiceClient(cc grpc.ClientConnInterface) DirectoryServiceClient {
	return &directoryServiceClient{cc}
}

func (c *directoryServiceClient) GetDirectory(ctx context.Context, in *GetDirectoryRequest, opts ...grpc.CallOption) (*Directory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Directory)
	err := c.cc.Invoke(ctx, DirectoryService_GetDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryServiceClient) GetDirectories(ctx context.Context, in *GetDirectoriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directory], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DirectoryService_ServiceDesc.Streams[0], DirectoryService_GetDirectories_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDirectoriesRequest, Directory]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirectoryService_GetDirectoriesClient = grpc.ServerStreamingClient[Directory]

func (c *directoryServiceClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*Directory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Directory)
	err := c.cc.Invoke(ctx, DirectoryService_CreateDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryServiceClient) PatchDirectory(ctx context.Context, in *AlterDirectoryRequest, opts ...grpc.CallOption) (*Directory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Directory)
	err := c.cc.Invoke(ctx, DirectoryService_PatchDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryServiceClient) DeleteDirectory(ctx context.Context, in *DeleteDirectoryRequest, opts ...grpc.CallOption) (*Directory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Directory)
	err := c.cc.Invoke(ctx, DirectoryService_DeleteDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryServiceServer is the server API for DirectoryService service.
// All implementations must embed UnimplementedDirectoryServiceServer
// for forward compatibility.
type DirectoryServiceServer interface {
	GetDirectory(context.Context, *GetDirectoryRequest) (*Directory, error)
	GetDirectories(*GetDirectoriesRequest, grpc.ServerStreamingServer[Directory]) error
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*Directory, error)
	PatchDirectory(context.Context, *AlterDirectoryRequest) (*Directory, error)
	DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*Directory, error)
	mustEmbedUnimplementedDirectoryServiceServer()
}

// UnimplementedDirectoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectoryServiceServer struct{}

func (UnimplementedDirectoryServiceServer) GetDirectory(context.Context, *GetDirectoryRequest) (*Directory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDirectory not implemented")
}
func (UnimplementedDirectoryServiceServer) GetDirectories(*GetDirectoriesRequest, grpc.ServerStreamingServer[Directory]) error {
	return status.Error(codes.Unimplemented, "method GetDirectories not implemented")
}
func (UnimplementedDirectoryServiceServer) CreateDirectory(context.Context, *CreateDirectoryRequest) (*Directory, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedDirectoryServiceServer) PatchDirectory(context.Context, *AlterDirectoryRequest) (*Directory, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchDirectory not implemented")
}
func (UnimplementedDirectoryServiceServer) DeleteDirectory(context.Context, *DeleteDirectoryRequest) (*Directory, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDirectory not implemented")
}
func (UnimplementedDirectoryServiceServer) mustEmbedUnimplementedDirectoryServiceServer() {}
func (UnimplementedDirectoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDirectoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectoryServiceServer will
// result in compilation errors.
type UnsafeDirectoryServiceServer interface {
	mustEmbedUnimplementedDirectoryServiceServer()
}

func RegisterDirectoryServiceServer(s grpc.ServiceRegistrar, srv DirectoryServiceServer) {
	// If the following call panics, it indicates UnimplementedDirectoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectoryService_ServiceDesc, srv)
}

func _DirectoryService_GetDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).GetDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_GetDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).GetDirectory(ctx, req.(*GetDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryService_GetDirectories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDirectoriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DirectoryServiceServer).GetDirectories(m, &grpc.GenericServerStream[GetDirectoriesRequest, Directory]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DirectoryService_GetDirectoriesServer = grpc.ServerStreamingServer[Directory]

func _DirectoryService_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_CreateDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryService_PatchDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlterDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).PatchDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_PatchDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).PatchDirectory(ctx, req.(*AlterDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryService_DeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServiceServer).DeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryService_DeleteDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServiceServer).DeleteDirectory(ctx, req.(*DeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectoryService_ServiceDesc is the grpc.ServiceDesc for DirectoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DirectoryService",
	HandlerType: (*DirectoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectory",
			Handler:    _DirectoryService_GetDirectory_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _DirectoryService_CreateDirectory_Handler,
		},
		{
			MethodName: "PatchDirectory",
			Handler:    _DirectoryService_PatchDirectory_Handler,
		},
		{
			MethodName: "DeleteDirectory",
			Handler:    _DirectoryService_DeleteDirectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDirectories",
			Handler:       _DirectoryService_GetDirectories_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/note.proto",
}

const (
	PermissionService_GetPermissions_FullMethodName     = "/proto.PermissionService/GetPermissions"
	PermissionService_CreatePermission_FullMethodName   = "/proto.PermissionService/CreatePermission"
	PermissionService_DeletePermission_FullMethodName   = "/proto.PermissionService/DeletePermission"
	PermissionService_ReplacePermissions_FullMethodName = "/proto.PermissionService/ReplacePermissions"
)

// PermissionServiceClient is the client API for PermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionServiceClient interface {
	GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error)
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionsResponse, error)
	DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*PermissionsResponse, error)
	ReplacePermissions(ctx context.Context, in *ReplacePermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error)
}

type permissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionServiceClient(cc grpc.ClientConnInterface) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) GetPermissions(ctx context.Context, in *GetPermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionsResponse)
	err := c.cc.Invoke(ctx, PermissionService_GetPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*PermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionsResponse)
	err := c.cc.Invoke(ctx, PermissionService_CreatePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*PermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionsResponse)
	err := c.cc.Invoke(ctx, PermissionService_DeletePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) ReplacePermissions(ctx context.Context, in *ReplacePermissionsRequest, opts ...grpc.CallOption) (*PermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionsResponse)
	err := c.cc.Invoke(ctx, PermissionService_ReplacePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServiceServer is the server API for PermissionService service.
// All implementations must embed UnimplementedPermissionServiceServer
// for forward compatibility.
type PermissionServiceServer interface {
	GetPermissions(context.Context, *GetPermissionsRequest) (*PermissionsResponse, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionsResponse, error)
	DeletePermission(context.Context, *DeletePermissionRequest) (*PermissionsResponse, error)
	ReplacePermissions(context.Context, *ReplacePermissionsRequest) (*PermissionsResponse, error)
	mustEmbedUnimplementedPermissionServiceServer()
}

// UnimplementedPermissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServiceServer struct{}

func (UnimplementedPermissionServiceServer) GetPermissions(context.Context, *GetPermissionsRequest) (*PermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissions not implemented")
}
func (UnimplementedPermissionServiceServer) CreatePermission(context.Context, *CreatePermissionRequest) (*PermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePermission not implemented")
}
func (UnimplementedPermissionServiceServer) DeletePermission(context.Context, *DeletePermissionRequest) (*PermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePermission not implemented")
}
func (UnimplementedPermissionServiceServer) ReplacePermissions(context.Context, *ReplacePermissionsRequest) (*PermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplacePermissions not implemented")
}
func (UnimplementedPermissionServiceServer) mustEmbedUnimplementedPermissionServiceServer() {}
func (UnimplementedPermissionServiceServer) testEmbeddedByValue()                           {}

// UnsafePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServiceServer will
// result in compilation errors.
type UnsafePermissionServiceServer interface {
	mustEmbedUnimplementedPermissionServiceServer()
}

func RegisterPermissionServiceServer(s grpc.ServiceRegistrar, srv PermissionServiceServer) {
	// If the following call panics, it indicates UnimplementedPermissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermissionService_ServiceDesc, srv)
}

func _PermissionService_GetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_GetPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GetPermissions(ctx, req.(*GetPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_CreatePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_DeletePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).DeletePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_DeletePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).DeletePermission(ctx, req.(*DeletePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_ReplacePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplacePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).ReplacePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_ReplacePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).ReplacePermissions(ctx, req.(*ReplacePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionService_ServiceDesc is the grpc.ServiceDesc for PermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPermissions",
			Handler:    _PermissionService_GetPermissions_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _PermissionService_CreatePermission_Handler,
		},
		{
			MethodName: "DeletePermission",
			Handler:    _PermissionService_DeletePermission_Handler,
		},
		{
			MethodName: "ReplacePermissions",
			Handler:    _PermissionService_ReplacePermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/note.proto",
}

const (
	NoteVersionService_GetNoteVersions_FullMethodName       = "/proto.NoteVersionService/GetNoteVersions"
	NoteVersionService_GetDirectoryActivity_FullMethodName  = "/proto.NoteVersionService/GetDirectoryActivity"
	NoteVersionService_GetNoteVersionContent_FullMethodName = "/proto.NoteVersionService/GetNoteVersionContent"
	NoteVersionService_RestoreNoteVersion_FullMethodName    = "/proto.NoteVersionService/RestoreNoteVersion"
)

// NoteVersionServiceClient is the client API for NoteVersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteVersionServiceClient interface {
	GetNoteVersions(ctx context.Context, in *GetNoteVersionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteVersionSummary], error)
	GetDirectoryActivity(ctx context.Context, in *GetDirectoryActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteVersionSummary], error)
	GetNoteVersionContent(ctx context.Context, in *GetNoteVersionContentRequest, opts ...grpc.CallOption) (*NoteVersionContent, error)
	RestoreNoteVersion(ctx context.Context, in *RestoreNoteVersionRequest, opts ...grpc.CallOption) (*Note, error)
}

type noteVersionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteVersionServiceClient(cc grpc.ClientConnInterface) NoteVersionServiceClient {
	return &noteVersionServiceClient{cc}
}

func (c *noteVersionServiceClient) GetNoteVersions(ctx context.Context, in *GetNoteVersionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteVersionSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteVersionService_ServiceDesc.Streams[0], NoteVersionService_GetNoteVersions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetNoteVersionsRequest, NoteVersionSummary]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteVersionService_GetNoteVersionsClient = grpc.ServerStreamingClient[NoteVersionSummary]

func (c *noteVersionServiceClient) GetDirectoryActivity(ctx context.Context, in *GetDirectoryActivityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteVersionSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NoteVersionService_ServiceDesc.Streams[1], NoteVersionService_GetDirectoryActivity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDirectoryActivityRequest, NoteVersionSummary]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteVersionService_GetDirectoryActivityClient = grpc.ServerStreamingClient[NoteVersionSummary]

func (c *noteVersionServiceClient) GetNoteVersionContent(ctx context.Context, in *GetNoteVersionContentRequest, opts ...grpc.CallOption) (*NoteVersionContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteVersionContent)
	err := c.cc.Invoke(ctx, NoteVersionService_GetNoteVersionContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteVersionServiceClient) RestoreNoteVersion(ctx context.Context, in *RestoreNoteVersionRequest, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteVersionService_RestoreNoteVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteVersionServiceServer is the server API for NoteVersionService service.
// All implementations must embed UnimplementedNoteVersionServiceServer
// for forward compatibility.
type NoteVersionServiceServer interface {
	GetNoteVersions(*GetNoteVersionsRequest, grpc.ServerStreamingServer[NoteVersionSummary]) error
	GetDirectoryActivity(*GetDirectoryActivityRequest, grpc.ServerStreamingServer[NoteVersionSummary]) error
	GetNoteVersionContent(context.Context, *GetNoteVersionContentRequest) (*NoteVersionContent, error)
	RestoreNoteVersion(context.Context, *RestoreNoteVersionRequest) (*Note, error)
	mustEmbedUnimplementedNoteVersionServiceServer()
}

// UnimplementedNoteVersionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteVersionServiceServer struct{}

func (UnimplementedNoteVersionServiceServer) GetNoteVersions(*GetNoteVersionsRequest, grpc.ServerStreamingServer[NoteVersionSummary]) error {
	return status.Error(codes.Unimplemented, "method GetNoteVersions not implemented")
}
func (UnimplementedNoteVersionServiceServer) GetDirectoryActivity(*GetDirectoryActivityRequest, grpc.ServerStreamingServer[NoteVersionSummary]) error {
	return status.Error(codes.Unimplemented, "method GetDirectoryActivity not implemented")
}
func (UnimplementedNoteVersionServiceServer) GetNoteVersionContent(context.Context, *GetNoteVersionContentRequest) (*NoteVersionContent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNoteVersionContent not implemented")
}
func (UnimplementedNoteVersionServiceServer) RestoreNoteVersion(context.Context, *RestoreNoteVersionRequest) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreNoteVersion not implemented")
}
func (UnimplementedNoteVersionServiceServer) mustEmbedUnimplementedNoteVersionServiceServer() {}
func (UnimplementedNoteVersionServiceServer) testEmbeddedByValue()                            {}

// UnsafeNoteVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteVersionServiceServer will
// result in compilation errors.
type UnsafeNoteVersionServiceServer interface {
	mustEmbedUnimplementedNoteVersionServiceServer()
}

func RegisterNoteVersionServiceServer(s grpc.ServiceRegistrar, srv NoteVersionServiceServer) {
	// If the following call panics, it indicates UnimplementedNoteVersionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteVersionService_ServiceDesc, srv)
}

func _NoteVersionService_GetNoteVersions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNoteVersionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteVersionServiceServer).GetNoteVersions(m, &grpc.GenericServerStream[GetNoteVersionsRequest, NoteVersionSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteVersionService_GetNoteVersionsServer = grpc.ServerStreamingServer[NoteVersionSummary]

func _NoteVersionService_GetDirectoryActivity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDirectoryActivityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteVersionServiceServer).GetDirectoryActivity(m, &grpc.GenericServerStream[GetDirectoryActivityRequest, NoteVersionSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NoteVersionService_GetDirectoryActivityServer = grpc.ServerStreamingServer[NoteVersionSummary]

func _NoteVersionService_GetNoteVersionContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteVersionContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteVersionServiceServer).GetNoteVersionContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteVersionService_GetNoteVersionContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteVersionServiceServer).GetNoteVersionContent(ctx, req.(*GetNoteVersionContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteVersionService_RestoreNoteVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreNoteVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteVersionServiceServer).RestoreNoteVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteVersionService_RestoreNoteVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteVersionServiceServer).RestoreNoteVersion(ctx, req.(*RestoreNoteVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteVersionService_ServiceDesc is the grpc.ServiceDesc for NoteVersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteVersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NoteVersionService",
	HandlerType: (*NoteVersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNoteVersionContent",
			Handler:    _NoteVersionService_GetNoteVersionContent_Handler,
		},
		{
			MethodName: "RestoreNoteVersion",
			Handler:    _NoteVersionService_RestoreNoteVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNoteVersions",
			Handler:       _NoteVersionService_GetNoteVersions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDirectoryActivity",
			Handler:       _NoteVersionService_GetDirectoryActivity_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/note.proto",
}
