// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: src/proto/note.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionObjectType int32

const (
	PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED PermissionObjectType = 0
	PermissionObjectType_PERMISSION_OBJECT_TYPE_NOTE        PermissionObjectType = 1
	PermissionObjectType_PERMISSION_OBJECT_TYPE_DIRECTORY   PermissionObjectType = 2
	PermissionObjectType_PERMISSION_OBJECT_TYPE_USER        PermissionObjectType = 3
)

// Enum value maps for PermissionObjectType.
var (
	PermissionObjectType_name = map[int32]string{
		0: "PERMISSION_OBJECT_TYPE_UNSPECIFIED",
		1: "PERMISSION_OBJECT_TYPE_NOTE",
		2: "PERMISSION_OBJECT_TYPE_DIRECTORY",
		3: "PERMISSION_OBJECT_TYPE_USER",
	}
	PermissionObjectType_value = map[string]int32{
		"PERMISSION_OBJECT_TYPE_UNSPECIFIED": 0,
		"PERMISSION_OBJECT_TYPE_NOTE":        1,
		"PERMISSION_OBJECT_TYPE_DIRECTORY":   2,
		"PERMISSION_OBJECT_TYPE_USER":        3,
	}
)

func (x PermissionObjectType) Enum() *PermissionObjectType {
	p := new(PermissionObjectType)
	*p = x
	return p
}

func (x PermissionObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_note_proto_enumTypes[0].Descriptor()
}

func (PermissionObjectType) Type() protoreflect.EnumType {
	return &file_src_proto_note_proto_enumTypes[0]
}

func (x PermissionObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionObjectType.Descriptor instead.
func (PermissionObjectType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{0}
}

type GetSearchNotesRequest_SearchType int32

const (
	GetSearchNotesRequest_Undefined     GetSearchNotesRequest_SearchType = 0 // default
	GetSearchNotesRequest_NoSearch      GetSearchNotesRequest_SearchType = 1 // just
	GetSearchNotesRequest_FullTextTitle GetSearchNotesRequest_SearchType = 2 // exact match search
	GetSearchNotesRequest_Fuzzy         GetSearchNotesRequest_SearchType = 3 // typo tolerant search
	GetSearchNotesRequest_Context       GetSearchNotesRequest_SearchType = 4 // semantic search using embeddings
)

// Enum value maps for GetSearchNotesRequest_SearchType.
var (
	GetSearchNotesRequest_SearchType_name = map[int32]string{
		0: "Undefined",
		1: "NoSearch",
		2: "FullTextTitle",
		3: "Fuzzy",
		4: "Context",
	}
	GetSearchNotesRequest_SearchType_value = map[string]int32{
		"Undefined":     0,
		"NoSearch":      1,
		"FullTextTitle": 2,
		"Fuzzy":         3,
		"Context":       4,
	}
)

func (x GetSearchNotesRequest_SearchType) Enum() *GetSearchNotesRequest_SearchType {
	p := new(GetSearchNotesRequest_SearchType)
	*p = x
	return p
}

func (x GetSearchNotesRequest_SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSearchNotesRequest_SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_note_proto_enumTypes[1].Descriptor()
}

func (GetSearchNotesRequest_SearchType) Type() protoreflect.EnumType {
	return &file_src_proto_note_proto_enumTypes[1]
}

func (x GetSearchNotesRequest_SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSearchNotesRequest_SearchType.Descriptor instead.
func (GetSearchNotesRequest_SearchType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{1, 0}
}

// Request for getting a note by id
type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{0}
}

func (x *GetNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSearchNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search parameters
	SearchType GetSearchNotesRequest_SearchType `protobuf:"varint,1,opt,name=search_type,json=searchType,proto3,enum=proto.GetSearchNotesRequest_SearchType" json:"search_type,omitempty"`
	Query      string                           `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Pagination
	Limit  int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// authentication
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchNotesRequest) Reset() {
	*x = GetSearchNotesRequest{}
	mi := &file_src_proto_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchNotesRequest) ProtoMessage() {}

func (x *GetSearchNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchNotesRequest.ProtoReflect.Descriptor instead.
func (*GetSearchNotesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchNotesRequest) GetSearchType() GetSearchNotesRequest_SearchType {
	if x != nil {
		return x.SearchType
	}
	return GetSearchNotesRequest_Undefined
}

func (x *GetSearchNotesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetSearchNotesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSearchNotesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSearchNotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response: represents a minimal Note for search results
type MinimalNote struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Id              string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Note ID (UUIDv4 string)
	Title           string                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId        string                    `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	UpdatedAt       *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StrippedContent string                    `protobuf:"bytes,5,opt,name=stripped_content,json=strippedContent,proto3" json:"stripped_content,omitempty"`
	Permissions     []*PermissionRelationship `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MinimalNote) Reset() {
	*x = MinimalNote{}
	mi := &file_src_proto_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalNote) ProtoMessage() {}

func (x *MinimalNote) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalNote.ProtoReflect.Descriptor instead.
func (*MinimalNote) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{2}
}

func (x *MinimalNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MinimalNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MinimalNote) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *MinimalNote) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MinimalNote) GetStrippedContent() string {
	if x != nil {
		return x.StrippedContent
	}
	return ""
}

func (x *MinimalNote) GetPermissions() []*PermissionRelationship {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Response: represents a Note
type Note struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AuthorId  string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// repeated NoteEmbedding embeddings = 6;
	Permissions   []*PermissionRelationship `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_src_proto_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{3}
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Note) GetPermissions() []*PermissionRelationship {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type NoteEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteEmbedding) Reset() {
	*x = NoteEmbedding{}
	mi := &file_src_proto_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEmbedding) ProtoMessage() {}

func (x *NoteEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEmbedding.ProtoReflect.Descriptor instead.
func (*NoteEmbedding) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{4}
}

func (x *NoteEmbedding) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *NoteEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// Request to add a note
type PostNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostNoteRequest) Reset() {
	*x = PostNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNoteRequest) ProtoMessage() {}

func (x *PostNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNoteRequest.ProtoReflect.Descriptor instead.
func (*PostNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{5}
}

func (x *PostNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *PostNoteRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// Request to delete a note
type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteNoteRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type AlterNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	AuthorId      *string                `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterNoteRequest) Reset() {
	*x = AlterNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterNoteRequest) ProtoMessage() {}

func (x *AlterNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterNoteRequest.ProtoReflect.Descriptor instead.
func (*AlterNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{7}
}

func (x *AlterNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlterNoteRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AlterNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *AlterNoteRequest) GetAuthorId() string {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return ""
}

type Directory struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                    `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                    `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ParentId      *string                   `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Relationships []*PermissionRelationship `protobuf:"bytes,7,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_src_proto_note_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{8}
}

func (x *Directory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Directory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Directory) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Directory) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Directory) GetRelationships() []*PermissionRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type GetDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryRequest) Reset() {
	*x = GetDirectoryRequest{}
	mi := &file_src_proto_note_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryRequest) ProtoMessage() {}

func (x *GetDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{9}
}

func (x *GetDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDirectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoriesRequest) Reset() {
	*x = GetDirectoriesRequest{}
	mi := &file_src_proto_note_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoriesRequest) ProtoMessage() {}

func (x *GetDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{10}
}

func (x *GetDirectoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDirectoriesRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *GetDirectoriesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetDirectoriesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	ParentId      *string                `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_src_proto_note_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDirectoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDirectoryRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CreateDirectoryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateDirectoryRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *CreateDirectoryRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreateDirectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AlterDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	ParentId      *string                `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterDirectoryRequest) Reset() {
	*x = AlterDirectoryRequest{}
	mi := &file_src_proto_note_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterDirectoryRequest) ProtoMessage() {}

func (x *AlterDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterDirectoryRequest.ProtoReflect.Descriptor instead.
func (*AlterDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{12}
}

func (x *AlterDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlterDirectoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AlterDirectoryRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *AlterDirectoryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AlterDirectoryRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *AlterDirectoryRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *AlterDirectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirectoryRequest) Reset() {
	*x = DeleteDirectoryRequest{}
	mi := &file_src_proto_note_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirectoryRequest) ProtoMessage() {}

func (x *DeleteDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirectoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDirectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PermissionSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    PermissionObjectType   `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSubject) Reset() {
	*x = PermissionSubject{}
	mi := &file_src_proto_note_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSubject) ProtoMessage() {}

func (x *PermissionSubject) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSubject.ProtoReflect.Descriptor instead.
func (*PermissionSubject) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{14}
}

func (x *PermissionSubject) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *PermissionSubject) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type PermissionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    PermissionObjectType   `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResource) Reset() {
	*x = PermissionResource{}
	mi := &file_src_proto_note_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResource) ProtoMessage() {}

func (x *PermissionResource) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResource.ProtoReflect.Descriptor instead.
func (*PermissionResource) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{15}
}

func (x *PermissionResource) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *PermissionResource) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type PermissionRelationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *PermissionSubject     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      *PermissionResource    `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRelationship) Reset() {
	*x = PermissionRelationship{}
	mi := &file_src_proto_note_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRelationship) ProtoMessage() {}

func (x *PermissionRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRelationship.ProtoReflect.Descriptor instead.
func (*PermissionRelationship) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{16}
}

func (x *PermissionRelationship) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *PermissionRelationship) GetSubject() *PermissionSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *PermissionRelationship) GetResource() *PermissionResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    PermissionObjectType   `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_src_proto_note_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{17}
}

func (x *GetPermissionsRequest) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *GetPermissionsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ObjectType    PermissionObjectType    `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                  `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relationship  *PermissionRelationship `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	UserId        string                  `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_src_proto_note_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePermissionRequest) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *CreatePermissionRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CreatePermissionRequest) GetRelationship() *PermissionRelationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

func (x *CreatePermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ObjectType    PermissionObjectType    `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                  `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relationship  *PermissionRelationship `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	UserId        string                  `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_src_proto_note_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePermissionRequest) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *DeletePermissionRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeletePermissionRequest) GetRelationship() *PermissionRelationship {
	if x != nil {
		return x.Relationship
	}
	return nil
}

func (x *DeletePermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ReplacePermissionsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ObjectType    PermissionObjectType      `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                    `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relationships []*PermissionRelationship `protobuf:"bytes,3,rep,name=relationships,proto3" json:"relationships,omitempty"`
	UserId        string                    `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplacePermissionsRequest) Reset() {
	*x = ReplacePermissionsRequest{}
	mi := &file_src_proto_note_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplacePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplacePermissionsRequest) ProtoMessage() {}

func (x *ReplacePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplacePermissionsRequest.ProtoReflect.Descriptor instead.
func (*ReplacePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{20}
}

func (x *ReplacePermissionsRequest) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *ReplacePermissionsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ReplacePermissionsRequest) GetRelationships() []*PermissionRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *ReplacePermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PermissionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ObjectType    PermissionObjectType      `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=proto.PermissionObjectType" json:"object_type,omitempty"`
	ObjectId      string                    `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relationships []*PermissionRelationship `protobuf:"bytes,3,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsResponse) Reset() {
	*x = PermissionsResponse{}
	mi := &file_src_proto_note_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsResponse) ProtoMessage() {}

func (x *PermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsResponse.ProtoReflect.Descriptor instead.
func (*PermissionsResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{21}
}

func (x *PermissionsResponse) GetObjectType() PermissionObjectType {
	if x != nil {
		return x.ObjectType
	}
	return PermissionObjectType_PERMISSION_OBJECT_TYPE_UNSPECIFIED
}

func (x *PermissionsResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *PermissionsResponse) GetRelationships() []*PermissionRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

// Versioning requests and responses
type NoteVersionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	NoteId        string                 `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	VersionIndex  int64                  `protobuf:"varint,3,opt,name=version_index,json=versionIndex,proto3" json:"version_index,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	IsSnapshot    bool                   `protobuf:"varint,6,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,7,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteVersionSummary) Reset() {
	*x = NoteVersionSummary{}
	mi := &file_src_proto_note_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteVersionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteVersionSummary) ProtoMessage() {}

func (x *NoteVersionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteVersionSummary.ProtoReflect.Descriptor instead.
func (*NoteVersionSummary) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{22}
}

func (x *NoteVersionSummary) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *NoteVersionSummary) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteVersionSummary) GetVersionIndex() int64 {
	if x != nil {
		return x.VersionIndex
	}
	return 0
}

func (x *NoteVersionSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NoteVersionSummary) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *NoteVersionSummary) GetIsSnapshot() bool {
	if x != nil {
		return x.IsSnapshot
	}
	return false
}

func (x *NoteVersionSummary) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetNoteVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteVersionsRequest) Reset() {
	*x = GetNoteVersionsRequest{}
	mi := &file_src_proto_note_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteVersionsRequest) ProtoMessage() {}

func (x *GetNoteVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetNoteVersionsRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{23}
}

func (x *GetNoteVersionsRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *GetNoteVersionsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetNoteVersionsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetNoteVersionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDirectoryActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryId   *string                `protobuf:"bytes,1,opt,name=directory_id,json=directoryId,proto3,oneof" json:"directory_id,omitempty"`
	MaxDepth      *int32                 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3,oneof" json:"max_depth,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryActivityRequest) Reset() {
	*x = GetDirectoryActivityRequest{}
	mi := &file_src_proto_note_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryActivityRequest) ProtoMessage() {}

func (x *GetDirectoryActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryActivityRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryActivityRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{24}
}

func (x *GetDirectoryActivityRequest) GetDirectoryId() string {
	if x != nil && x.DirectoryId != nil {
		return *x.DirectoryId
	}
	return ""
}

func (x *GetDirectoryActivityRequest) GetMaxDepth() int32 {
	if x != nil && x.MaxDepth != nil {
		return *x.MaxDepth
	}
	return 0
}

func (x *GetDirectoryActivityRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetDirectoryActivityRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetDirectoryActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NoteVersionContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	VersionIndex  int64                  `protobuf:"varint,2,opt,name=version_index,json=versionIndex,proto3" json:"version_index,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteVersionContent) Reset() {
	*x = NoteVersionContent{}
	mi := &file_src_proto_note_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteVersionContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteVersionContent) ProtoMessage() {}

func (x *NoteVersionContent) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteVersionContent.ProtoReflect.Descriptor instead.
func (*NoteVersionContent) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{25}
}

func (x *NoteVersionContent) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteVersionContent) GetVersionIndex() int64 {
	if x != nil {
		return x.VersionIndex
	}
	return 0
}

func (x *NoteVersionContent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NoteVersionContent) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *NoteVersionContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteVersionContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetNoteVersionContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	VersionIndex  int64                  `protobuf:"varint,2,opt,name=version_index,json=versionIndex,proto3" json:"version_index,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteVersionContentRequest) Reset() {
	*x = GetNoteVersionContentRequest{}
	mi := &file_src_proto_note_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteVersionContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteVersionContentRequest) ProtoMessage() {}

func (x *GetNoteVersionContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteVersionContentRequest.ProtoReflect.Descriptor instead.
func (*GetNoteVersionContentRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{26}
}

func (x *GetNoteVersionContentRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *GetNoteVersionContentRequest) GetVersionIndex() int64 {
	if x != nil {
		return x.VersionIndex
	}
	return 0
}

func (x *GetNoteVersionContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RestoreNoteVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	VersionIndex  int64                  `protobuf:"varint,2,opt,name=version_index,json=versionIndex,proto3" json:"version_index,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreNoteVersionRequest) Reset() {
	*x = RestoreNoteVersionRequest{}
	mi := &file_src_proto_note_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreNoteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreNoteVersionRequest) ProtoMessage() {}

func (x *RestoreNoteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreNoteVersionRequest.ProtoReflect.Descriptor instead.
func (*RestoreNoteVersionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{27}
}

func (x *RestoreNoteVersionRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *RestoreNoteVersionRequest) GetVersionIndex() int64 {
	if x != nil {
		return x.VersionIndex
	}
	return 0
}

func (x *RestoreNoteVersionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_src_proto_note_proto protoreflect.FileDescriptor

const file_src_proto_note_proto_rawDesc = "" +
	"\n" +
	"\x14src/proto/note.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x0eGetNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x94\x02\n" +
	"\x15GetSearchNotesRequest\x12H\n" +
	"\vsearch_type\x18\x01 \x01(\x0e2'.proto.GetSearchNotesRequest.SearchTypeR\n" +
	"searchType\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"T\n" +
	"\n" +
	"SearchType\x12\r\n" +
	"\tUndefined\x10\x00\x12\f\n" +
	"\bNoSearch\x10\x01\x12\x11\n" +
	"\rFullTextTitle\x10\x02\x12\t\n" +
	"\x05Fuzzy\x10\x03\x12\v\n" +
	"\aContext\x10\x04\"\xf7\x01\n" +
	"\vMinimalNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x10stripped_content\x18\x05 \x01(\tR\x0fstrippedContent\x12?\n" +
	"\vpermissions\x18\x06 \x03(\v2\x1d.proto.PermissionRelationshipR\vpermissions\"\xe5\x01\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12?\n" +
	"\vpermissions\x18\a \x03(\v2\x1d.proto.PermissionRelationshipR\vpermissionsJ\x04\b\x06\x10\a\"C\n" +
	"\rNoteEmbedding\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\"o\n" +
	"\x0fPostNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorIdB\n" +
	"\n" +
	"\b_content\"@\n" +
	"\x11DeleteNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\"\xa2\x01\n" +
	"\x10AlterNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x04 \x01(\tH\x02R\bauthorId\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\f\n" +
	"\n" +
	"_author_id\"\x86\x02\n" +
	"\tDirectory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12 \n" +
	"\tparent_id\x18\x06 \x01(\tH\x00R\bparentId\x88\x01\x01\x12C\n" +
	"\rrelationships\x18\a \x03(\v2\x1d.proto.PermissionRelationshipR\rrelationshipsB\f\n" +
	"\n" +
	"_parent_id\">\n" +
	"\x13GetDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xad\x01\n" +
	"\x15GetDirectoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x02R\x06offset\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\x95\x02\n" +
	"\x16CreateDirectoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x05 \x01(\tH\x03R\bparentId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userIdB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\f\n" +
	"\n" +
	"_parent_id\"\xb2\x02\n" +
	"\x15AlterDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x03R\bimageUrl\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x06 \x01(\tH\x04R\bparentId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userIdB\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\f\n" +
	"\n" +
	"_parent_id\"A\n" +
	"\x16DeleteDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"n\n" +
	"\x11PermissionSubject\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"o\n" +
	"\x12PermissionResource\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"\x9f\x01\n" +
	"\x16PermissionRelationship\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x122\n" +
	"\asubject\x18\x02 \x01(\v2\x18.proto.PermissionSubjectR\asubject\x125\n" +
	"\bresource\x18\x03 \x01(\v2\x19.proto.PermissionResourceR\bresource\"\x8b\x01\n" +
	"\x15GetPermissionsRequest\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xd0\x01\n" +
	"\x17CreatePermissionRequest\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12A\n" +
	"\frelationship\x18\x03 \x01(\v2\x1d.proto.PermissionRelationshipR\frelationship\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xd0\x01\n" +
	"\x17DeletePermissionRequest\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12A\n" +
	"\frelationship\x18\x03 \x01(\v2\x1d.proto.PermissionRelationshipR\frelationship\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xd4\x01\n" +
	"\x19ReplacePermissionsRequest\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12C\n" +
	"\rrelationships\x18\x03 \x03(\v2\x1d.proto.PermissionRelationshipR\rrelationships\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xb5\x01\n" +
	"\x13PermissionsResponse\x12<\n" +
	"\vobject_type\x18\x01 \x01(\x0e2\x1b.proto.PermissionObjectTypeR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12C\n" +
	"\rrelationships\x18\x03 \x03(\v2\x1d.proto.PermissionRelationshipR\rrelationships\"\x8b\x02\n" +
	"\x12NoteVersionSummary\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\tR\x06noteId\x12#\n" +
	"\rversion_index\x18\x03 \x01(\x03R\fversionIndex\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x1f\n" +
	"\vis_snapshot\x18\x06 \x01(\bR\n" +
	"isSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\a \x01(\tR\n" +
	"snapshotId\"\x97\x01\n" +
	"\x16GetNoteVersionsRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userIdB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\xec\x01\n" +
	"\x1bGetDirectoryActivityRequest\x12&\n" +
	"\fdirectory_id\x18\x01 \x01(\tH\x00R\vdirectoryId\x88\x01\x01\x12 \n" +
	"\tmax_depth\x18\x02 \x01(\x05H\x01R\bmaxDepth\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x03R\x06offset\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userIdB\x0f\n" +
	"\r_directory_idB\f\n" +
	"\n" +
	"_max_depthB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\xda\x01\n" +
	"\x12NoteVersionContent\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12#\n" +
	"\rversion_index\x18\x02 \x01(\x03R\fversionIndex\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"u\n" +
	"\x1cGetNoteVersionContentRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12#\n" +
	"\rversion_index\x18\x02 \x01(\x03R\fversionIndex\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"r\n" +
	"\x19RestoreNoteVersionRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12#\n" +
	"\rversion_index\x18\x02 \x01(\x03R\fversionIndex\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId*\xa6\x01\n" +
	"\x14PermissionObjectType\x12&\n" +
	"\"PERMISSION_OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPERMISSION_OBJECT_TYPE_NOTE\x10\x01\x12$\n" +
	" PERMISSION_OBJECT_TYPE_DIRECTORY\x10\x02\x12\x1f\n" +
	"\x1bPERMISSION_OBJECT_TYPE_USER\x10\x032\x98\x02\n" +
	"\vNoteService\x12-\n" +
	"\aGetNote\x12\x15.proto.GetNoteRequest\x1a\v.proto.Note\x12/\n" +
	"\bPostNote\x12\x16.proto.PostNoteRequest\x1a\v.proto.Note\x121\n" +
	"\tPatchNote\x12\x17.proto.AlterNoteRequest\x1a\v.proto.Note\x123\n" +
	"\n" +
	"DeleteNote\x12\x18.proto.DeleteNoteRequest\x1a\v.proto.Note\x12A\n" +
	"\vSearchNotes\x12\x1c.proto.GetSearchNotesRequest\x1a\x12.proto.MinimalNote0\x012\xde\x02\n" +
	"\x10DirectoryService\x12<\n" +
	"\fGetDirectory\x12\x1a.proto.GetDirectoryRequest\x1a\x10.proto.Directory\x12B\n" +
	"\x0eGetDirectories\x12\x1c.proto.GetDirectoriesRequest\x1a\x10.proto.Directory0\x01\x12B\n" +
	"\x0fCreateDirectory\x12\x1d.proto.CreateDirectoryRequest\x1a\x10.proto.Directory\x12@\n" +
	"\x0ePatchDirectory\x12\x1c.proto.AlterDirectoryRequest\x1a\x10.proto.Directory\x12B\n" +
	"\x0fDeleteDirectory\x12\x1d.proto.DeleteDirectoryRequest\x1a\x10.proto.Directory2\xd3\x02\n" +
	"\x11PermissionService\x12J\n" +
	"\x0eGetPermissions\x12\x1c.proto.GetPermissionsRequest\x1a\x1a.proto.PermissionsResponse\x12N\n" +
	"\x10CreatePermission\x12\x1e.proto.CreatePermissionRequest\x1a\x1a.proto.PermissionsResponse\x12N\n" +
	"\x10DeletePermission\x12\x1e.proto.DeletePermissionRequest\x1a\x1a.proto.PermissionsResponse\x12R\n" +
	"\x12ReplacePermissions\x12 .proto.ReplacePermissionsRequest\x1a\x1a.proto.PermissionsResponse2\xda\x02\n" +
	"\x12NoteVersionService\x12M\n" +
	"\x0fGetNoteVersions\x12\x1d.proto.GetNoteVersionsRequest\x1a\x19.proto.NoteVersionSummary0\x01\x12W\n" +
	"\x14GetDirectoryActivity\x12\".proto.GetDirectoryActivityRequest\x1a\x19.proto.NoteVersionSummary0\x01\x12W\n" +
	"\x15GetNoteVersionContent\x12#.proto.GetNoteVersionContentRequest\x1a\x19.proto.NoteVersionContent\x12C\n" +
	"\x12RestoreNoteVersion\x12 .proto.RestoreNoteVersionRequest\x1a\v.proto.NoteB1Z/github.com/KuramaSyu/Wersu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_note_proto_rawDescOnce sync.Once
	file_src_proto_note_proto_rawDescData []byte
)

func file_src_proto_note_proto_rawDescGZIP() []byte {
	file_src_proto_note_proto_rawDescOnce.Do(func() {
		file_src_proto_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_note_proto_rawDesc), len(file_src_proto_note_proto_rawDesc)))
	})
	return file_src_proto_note_proto_rawDescData
}

var file_src_proto_note_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_proto_note_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_src_proto_note_proto_goTypes = []any{
	(PermissionObjectType)(0),             // 0: proto.PermissionObjectType
	(GetSearchNotesRequest_SearchType)(0), // 1: proto.GetSearchNotesRequest.SearchType
	(*GetNoteRequest)(nil),                // 2: proto.GetNoteRequest
	(*GetSearchNotesRequest)(nil),         // 3: proto.GetSearchNotesRequest
	(*MinimalNote)(nil),                   // 4: proto.MinimalNote
	(*Note)(nil),                          // 5: proto.Note
	(*NoteEmbedding)(nil),                 // 6: proto.NoteEmbedding
	(*PostNoteRequest)(nil),               // 7: proto.PostNoteRequest
	(*DeleteNoteRequest)(nil),             // 8: proto.DeleteNoteRequest
	(*AlterNoteRequest)(nil),              // 9: proto.AlterNoteRequest
	(*Directory)(nil),                     // 10: proto.Directory
	(*GetDirectoryRequest)(nil),           // 11: proto.GetDirectoryRequest
	(*GetDirectoriesRequest)(nil),         // 12: proto.GetDirectoriesRequest
	(*CreateDirectoryRequest)(nil),        // 13: proto.CreateDirectoryRequest
	(*AlterDirectoryRequest)(nil),         // 14: proto.AlterDirectoryRequest
	(*DeleteDirectoryRequest)(nil),        // 15: proto.DeleteDirectoryRequest
	(*PermissionSubject)(nil),             // 16: proto.PermissionSubject
	(*PermissionResource)(nil),            // 17: proto.PermissionResource
	(*PermissionRelationship)(nil),        // 18: proto.PermissionRelationship
	(*GetPermissionsRequest)(nil),         // 19: proto.GetPermissionsRequest
	(*CreatePermissionRequest)(nil),       // 20: proto.CreatePermissionRequest
	(*DeletePermissionRequest)(nil),       // 21: proto.DeletePermissionRequest
	(*ReplacePermissionsRequest)(nil),     // 22: proto.ReplacePermissionsRequest
	(*PermissionsResponse)(nil),           // 23: proto.PermissionsResponse
	(*NoteVersionSummary)(nil),            // 24: proto.NoteVersionSummary
	(*GetNoteVersionsRequest)(nil),        // 25: proto.GetNoteVersionsRequest
	(*GetDirectoryActivityRequest)(nil),   // 26: proto.GetDirectoryActivityRequest
	(*NoteVersionContent)(nil),            // 27: proto.NoteVersionContent
	(*GetNoteVersionContentRequest)(nil),  // 28: proto.GetNoteVersionContentRequest
	(*RestoreNoteVersionRequest)(nil),     // 29: proto.RestoreNoteVersionRequest
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
}
var file_src_proto_note_proto_depIdxs = []int32{
	1,  // 0: proto.GetSearchNotesRequest.search_type:type_name -> proto.GetSearchNotesRequest.SearchType
	30, // 1: proto.MinimalNote.updated_at:type_name -> google.protobuf.Timestamp
	18, // 2: proto.MinimalNote.permissions:type_name -> proto.PermissionRelationship
	30, // 3: proto.Note.updated_at:type_name -> google.protobuf.Timestamp
	18, // 4: proto.Note.permissions:type_name -> proto.PermissionRelationship
	18, // 5: proto.Directory.relationships:type_name -> proto.PermissionRelationship
	0,  // 6: proto.PermissionSubject.object_type:type_name -> proto.PermissionObjectType
	0,  // 7: proto.PermissionResource.object_type:type_name -> proto.PermissionObjectType
	16, // 8: proto.PermissionRelationship.subject:type_name -> proto.PermissionSubject
	17, // 9: proto.PermissionRelationship.resource:type_name -> proto.PermissionResource
	0,  // 10: proto.GetPermissionsRequest.object_type:type_name -> proto.PermissionObjectType
	0,  // 11: proto.CreatePermissionRequest.object_type:type_name -> proto.PermissionObjectType
	18, // 12: proto.CreatePermissionRequest.relationship:type_name -> proto.PermissionRelationship
	0,  // 13: proto.DeletePermissionRequest.object_type:type_name -> proto.PermissionObjectType
	18, // 14: proto.DeletePermissionRequest.relationship:type_name -> proto.PermissionRelationship
	0,  // 15: proto.ReplacePermissionsRequest.object_type:type_name -> proto.PermissionObjectType
	18, // 16: proto.ReplacePermissionsRequest.relationships:type_name -> proto.PermissionRelationship
	0,  // 17: proto.PermissionsResponse.object_type:type_name -> proto.PermissionObjectType
	18, // 18: proto.PermissionsResponse.relationships:type_name -> proto.PermissionRelationship
	30, // 19: proto.NoteVersionSummary.created_at:type_name -> google.protobuf.Timestamp
	30, // 20: proto.NoteVersionContent.created_at:type_name -> google.protobuf.Timestamp
	2,  // 21: proto.NoteService.GetNote:input_type -> proto.GetNoteRequest
	7,  // 22: proto.NoteService.PostNote:input_type -> proto.PostNoteRequest
	9,  // 23: proto.NoteService.PatchNote:input_type -> proto.AlterNoteRequest
	8,  // 24: proto.NoteService.DeleteNote:input_type -> proto.DeleteNoteRequest
	3,  // 25: proto.NoteService.SearchNotes:input_type -> proto.GetSearchNotesRequest
	11, // 26: proto.DirectoryService.GetDirectory:input_type -> proto.GetDirectoryRequest
	12, // 27: proto.DirectoryService.GetDirectories:input_type -> proto.GetDirectoriesRequest
	13, // 28: proto.DirectoryService.CreateDirectory:input_type -> proto.CreateDirectoryRequest
	14, // 29: proto.DirectoryService.PatchDirectory:input_type -> proto.AlterDirectoryRequest
	15, // 30: proto.DirectoryService.DeleteDirectory:input_type -> proto.DeleteDirectoryRequest
	19, // 31: proto.PermissionService.GetPermissions:input_type -> proto.GetPermissionsRequest
	20, // 32: proto.PermissionService.CreatePermission:input_type -> proto.CreatePermissionRequest
	21, // 33: proto.PermissionService.DeletePermission:input_type -> proto.DeletePermissionRequest
	22, // 34: proto.PermissionService.ReplacePermissions:input_type -> proto.ReplacePermissionsRequest
	25, // 35: proto.NoteVersionService.GetNoteVersions:input_type -> proto.GetNoteVersionsRequest
	26, // 36: proto.NoteVersionService.GetDirectoryActivity:input_type -> proto.GetDirectoryActivityRequest
	28, // 37: proto.NoteVersionService.GetNoteVersionContent:input_type -> proto.GetNoteVersionContentRequest
	29, // 38: proto.NoteVersionService.RestoreNoteVersion:input_type -> proto.RestoreNoteVersionRequest
	5,  // 39: proto.NoteService.GetNote:output_type -> proto.Note
	5,  // 40: proto.NoteService.PostNote:output_type -> proto.Note
	5,  // 41: proto.NoteService.PatchNote:output_type -> proto.Note
	5,  // 42: proto.NoteService.DeleteNote:output_type -> proto.Note
	4,  // 43: proto.NoteService.SearchNotes:output_type -> proto.MinimalNote
	10, // 44: proto.DirectoryService.GetDirectory:output_type -> proto.Directory
	10, // 45: proto.DirectoryService.GetDirectories:output_type -> proto.Directory
	10, // 46: proto.DirectoryService.CreateDirectory:output_type -> proto.Directory
	10, // 47: proto.DirectoryService.PatchDirectory:output_type -> proto.Directory
	10, // 48: proto.DirectoryService.DeleteDirectory:output_type -> proto.Directory
	23, // 49: proto.PermissionService.GetPermissions:output_type -> proto.PermissionsResponse
	23, // 50: proto.PermissionService.CreatePermission:output_type -> proto.PermissionsResponse
	23, // 51: proto.PermissionService.DeletePermission:output_type -> proto.PermissionsResponse
	23, // 52: proto.PermissionService.ReplacePermissions:output_type -> proto.PermissionsResponse
	24, // 53: proto.NoteVersionService.GetNoteVersions:output_type -> proto.NoteVersionSummary
	24, // 54: proto.NoteVersionService.GetDirectoryActivity:output_type -> proto.NoteVersionSummary
	27, // 55: proto.NoteVersionService.GetNoteVersionContent:output_type -> proto.NoteVersionContent
	5,  // 56: proto.NoteVersionService.RestoreNoteVersion:output_type -> proto.Note
	39, // [39:57] is the sub-list for method output_type
	21, // [21:39] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_src_proto_note_proto_init() }
func file_src_proto_note_proto_init() {
	if File_src_proto_note_proto != nil {
		return
	}
	file_src_proto_note_proto_msgTypes[5].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[7].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[8].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[10].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[11].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[12].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[23].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_note_proto_rawDesc), len(file_src_proto_note_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_src_proto_note_proto_goTypes,
		DependencyIndexes: file_src_proto_note_proto_depIdxs,
		EnumInfos:         file_src_proto_note_proto_enumTypes,
		MessageInfos:      file_src_proto_note_proto_msgTypes,
	}.Build()
	File_src_proto_note_proto = out.File
	file_src_proto_note_proto_goTypes = nil
	file_src_proto_note_proto_depIdxs = nil
}
