// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: src/proto/note.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSearchNotesRequest_SearchType int32

const (
	GetSearchNotesRequest_Undefined     GetSearchNotesRequest_SearchType = 0 // default
	GetSearchNotesRequest_NoSearch      GetSearchNotesRequest_SearchType = 1 // just
	GetSearchNotesRequest_FullTextTitle GetSearchNotesRequest_SearchType = 2 // exact match search
	GetSearchNotesRequest_Fuzzy         GetSearchNotesRequest_SearchType = 3 // typo tolerant search
	GetSearchNotesRequest_Context       GetSearchNotesRequest_SearchType = 4 // semantic search using embeddings
)

// Enum value maps for GetSearchNotesRequest_SearchType.
var (
	GetSearchNotesRequest_SearchType_name = map[int32]string{
		0: "Undefined",
		1: "NoSearch",
		2: "FullTextTitle",
		3: "Fuzzy",
		4: "Context",
	}
	GetSearchNotesRequest_SearchType_value = map[string]int32{
		"Undefined":     0,
		"NoSearch":      1,
		"FullTextTitle": 2,
		"Fuzzy":         3,
		"Context":       4,
	}
)

func (x GetSearchNotesRequest_SearchType) Enum() *GetSearchNotesRequest_SearchType {
	p := new(GetSearchNotesRequest_SearchType)
	*p = x
	return p
}

func (x GetSearchNotesRequest_SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSearchNotesRequest_SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_note_proto_enumTypes[0].Descriptor()
}

func (GetSearchNotesRequest_SearchType) Type() protoreflect.EnumType {
	return &file_src_proto_note_proto_enumTypes[0]
}

func (x GetSearchNotesRequest_SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSearchNotesRequest_SearchType.Descriptor instead.
func (GetSearchNotesRequest_SearchType) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{1, 0}
}

// Request for getting a note by id
type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{0}
}

func (x *GetNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetNoteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSearchNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search parameters
	SearchType GetSearchNotesRequest_SearchType `protobuf:"varint,1,opt,name=search_type,json=searchType,proto3,enum=proto.GetSearchNotesRequest_SearchType" json:"search_type,omitempty"`
	Query      string                           `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Pagination
	Limit  int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// authentication
	UserId        int32 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchNotesRequest) Reset() {
	*x = GetSearchNotesRequest{}
	mi := &file_src_proto_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchNotesRequest) ProtoMessage() {}

func (x *GetSearchNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchNotesRequest.ProtoReflect.Descriptor instead.
func (*GetSearchNotesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchNotesRequest) GetSearchType() GetSearchNotesRequest_SearchType {
	if x != nil {
		return x.SearchType
	}
	return GetSearchNotesRequest_Undefined
}

func (x *GetSearchNotesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GetSearchNotesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSearchNotesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetSearchNotesRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Response: represents a minimal Note for search results
type MinimalNote struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Note ID (eg 42)
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AuthorId        int32                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StrippedContent string                 `protobuf:"bytes,5,opt,name=stripped_content,json=strippedContent,proto3" json:"stripped_content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MinimalNote) Reset() {
	*x = MinimalNote{}
	mi := &file_src_proto_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalNote) ProtoMessage() {}

func (x *MinimalNote) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalNote.ProtoReflect.Descriptor instead.
func (*MinimalNote) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{2}
}

func (x *MinimalNote) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MinimalNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MinimalNote) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *MinimalNote) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MinimalNote) GetStrippedContent() string {
	if x != nil {
		return x.StrippedContent
	}
	return ""
}

// Response: represents a Note
type Note struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content   string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AuthorId  int32                  `protobuf:"varint,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// repeated NoteEmbedding embeddings = 6;
	Permissions   []*NotePermission `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_src_proto_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{3}
}

func (x *Note) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Note) GetPermissions() []*NotePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type NoteEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteEmbedding) Reset() {
	*x = NoteEmbedding{}
	mi := &file_src_proto_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteEmbedding) ProtoMessage() {}

func (x *NoteEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteEmbedding.ProtoReflect.Descriptor instead.
func (*NoteEmbedding) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{4}
}

func (x *NoteEmbedding) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *NoteEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type NotePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotePermission) Reset() {
	*x = NotePermission{}
	mi := &file_src_proto_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotePermission) ProtoMessage() {}

func (x *NotePermission) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotePermission.ProtoReflect.Descriptor instead.
func (*NotePermission) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{5}
}

func (x *NotePermission) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// Request to add/Update a note
type PostNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	AuthorId      int32                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostNoteRequest) Reset() {
	*x = PostNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNoteRequest) ProtoMessage() {}

func (x *PostNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNoteRequest.ProtoReflect.Descriptor instead.
func (*PostNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{6}
}

func (x *PostNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *PostNoteRequest) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type AlterNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	AuthorId      *int32                 `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3,oneof" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterNoteRequest) Reset() {
	*x = AlterNoteRequest{}
	mi := &file_src_proto_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterNoteRequest) ProtoMessage() {}

func (x *AlterNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterNoteRequest.ProtoReflect.Descriptor instead.
func (*AlterNoteRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_note_proto_rawDescGZIP(), []int{7}
}

func (x *AlterNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlterNoteRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AlterNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *AlterNoteRequest) GetAuthorId() int32 {
	if x != nil && x.AuthorId != nil {
		return *x.AuthorId
	}
	return 0
}

var File_src_proto_note_proto protoreflect.FileDescriptor

const file_src_proto_note_proto_rawDesc = "" +
	"\n" +
	"\x14src/proto/note.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x0eGetNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"\x94\x02\n" +
	"\x15GetSearchNotesRequest\x12H\n" +
	"\vsearch_type\x18\x01 \x01(\x0e2'.proto.GetSearchNotesRequest.SearchTypeR\n" +
	"searchType\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x05R\x06userId\"T\n" +
	"\n" +
	"SearchType\x12\r\n" +
	"\tUndefined\x10\x00\x12\f\n" +
	"\bNoSearch\x10\x01\x12\x11\n" +
	"\rFullTextTitle\x10\x02\x12\t\n" +
	"\x05Fuzzy\x10\x03\x12\v\n" +
	"\aContext\x10\x04\"\xb6\x01\n" +
	"\vMinimalNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x05R\bauthorId\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x10stripped_content\x18\x05 \x01(\tR\x0fstrippedContent\"\xdd\x01\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\x05R\bauthorId\x127\n" +
	"\vpermissions\x18\a \x03(\v2\x15.proto.NotePermissionR\vpermissionsJ\x04\b\x06\x10\a\"C\n" +
	"\rNoteEmbedding\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\")\n" +
	"\x0eNotePermission\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"o\n" +
	"\x0fPostNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x05R\bauthorIdB\n" +
	"\n" +
	"\b_content\"\xa2\x01\n" +
	"\x10AlterNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01\x12 \n" +
	"\tauthor_id\x18\x04 \x01(\x05H\x02R\bauthorId\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\f\n" +
	"\n" +
	"_author_id2\xb0\x01\n" +
	"\vNoteService\x12-\n" +
	"\aGetNote\x12\x15.proto.GetNoteRequest\x1a\v.proto.Note\x12/\n" +
	"\bPostNote\x12\x16.proto.PostNoteRequest\x1a\v.proto.Note\x12A\n" +
	"\vSearchNotes\x12\x1c.proto.GetSearchNotesRequest\x1a\x12.proto.MinimalNote0\x01B1Z/github.com/KuramaSyu/Wersu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_note_proto_rawDescOnce sync.Once
	file_src_proto_note_proto_rawDescData []byte
)

func file_src_proto_note_proto_rawDescGZIP() []byte {
	file_src_proto_note_proto_rawDescOnce.Do(func() {
		file_src_proto_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_note_proto_rawDesc), len(file_src_proto_note_proto_rawDesc)))
	})
	return file_src_proto_note_proto_rawDescData
}

var file_src_proto_note_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_note_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_src_proto_note_proto_goTypes = []any{
	(GetSearchNotesRequest_SearchType)(0), // 0: proto.GetSearchNotesRequest.SearchType
	(*GetNoteRequest)(nil),                // 1: proto.GetNoteRequest
	(*GetSearchNotesRequest)(nil),         // 2: proto.GetSearchNotesRequest
	(*MinimalNote)(nil),                   // 3: proto.MinimalNote
	(*Note)(nil),                          // 4: proto.Note
	(*NoteEmbedding)(nil),                 // 5: proto.NoteEmbedding
	(*NotePermission)(nil),                // 6: proto.NotePermission
	(*PostNoteRequest)(nil),               // 7: proto.PostNoteRequest
	(*AlterNoteRequest)(nil),              // 8: proto.AlterNoteRequest
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_src_proto_note_proto_depIdxs = []int32{
	0, // 0: proto.GetSearchNotesRequest.search_type:type_name -> proto.GetSearchNotesRequest.SearchType
	9, // 1: proto.MinimalNote.updated_at:type_name -> google.protobuf.Timestamp
	9, // 2: proto.Note.updated_at:type_name -> google.protobuf.Timestamp
	6, // 3: proto.Note.permissions:type_name -> proto.NotePermission
	1, // 4: proto.NoteService.GetNote:input_type -> proto.GetNoteRequest
	7, // 5: proto.NoteService.PostNote:input_type -> proto.PostNoteRequest
	2, // 6: proto.NoteService.SearchNotes:input_type -> proto.GetSearchNotesRequest
	4, // 7: proto.NoteService.GetNote:output_type -> proto.Note
	4, // 8: proto.NoteService.PostNote:output_type -> proto.Note
	3, // 9: proto.NoteService.SearchNotes:output_type -> proto.MinimalNote
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_proto_note_proto_init() }
func file_src_proto_note_proto_init() {
	if File_src_proto_note_proto != nil {
		return
	}
	file_src_proto_note_proto_msgTypes[6].OneofWrappers = []any{}
	file_src_proto_note_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_note_proto_rawDesc), len(file_src_proto_note_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_note_proto_goTypes,
		DependencyIndexes: file_src_proto_note_proto_depIdxs,
		EnumInfos:         file_src_proto_note_proto_enumTypes,
		MessageInfos:      file_src_proto_note_proto_msgTypes,
	}.Build()
	File_src_proto_note_proto = out.File
	file_src_proto_note_proto_goTypes = nil
	file_src_proto_note_proto_depIdxs = nil
}
