// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: src/proto/sharing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission level of a share.
type SharePermission int32

const (
	SharePermission_SHARE_PERMISSION_UNSPECIFIED SharePermission = 0
	SharePermission_SHARE_PERMISSION_READ        SharePermission = 1
	SharePermission_SHARE_PERMISSION_WRITE       SharePermission = 2
)

// Enum value maps for SharePermission.
var (
	SharePermission_name = map[int32]string{
		0: "SHARE_PERMISSION_UNSPECIFIED",
		1: "SHARE_PERMISSION_READ",
		2: "SHARE_PERMISSION_WRITE",
	}
	SharePermission_value = map[string]int32{
		"SHARE_PERMISSION_UNSPECIFIED": 0,
		"SHARE_PERMISSION_READ":        1,
		"SHARE_PERMISSION_WRITE":       2,
	}
)

func (x SharePermission) Enum() *SharePermission {
	p := new(SharePermission)
	*p = x
	return p
}

func (x SharePermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SharePermission) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_sharing_proto_enumTypes[0].Descriptor()
}

func (SharePermission) Type() protoreflect.EnumType {
	return &file_src_proto_sharing_proto_enumTypes[0]
}

func (x SharePermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SharePermission.Descriptor instead.
func (SharePermission) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{0}
}

// String wrapper: field omitted = leave unchanged, null_value = explicit NULL,
// value = use the provided string.
type NullableString struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*NullableString_Value
	//	*NullableString_NullValue
	Kind          isNullableString_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	mi := &file_src_proto_sharing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{0}
}

func (x *NullableString) GetKind() isNullableString_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *NullableString) GetValue() string {
	if x != nil {
		if x, ok := x.Kind.(*NullableString_Value); ok {
			return x.Value
		}
	}
	return ""
}

func (x *NullableString) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*NullableString_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

type isNullableString_Kind interface {
	isNullableString_Kind()
}

type NullableString_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type NullableString_NullValue struct {
	NullValue bool `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,oneof"`
}

func (*NullableString_Value) isNullableString_Kind() {}

func (*NullableString_NullValue) isNullableString_Kind() {}

// Timestamp wrapper: field omitted = leave unchanged, null_value = explicit NULL,
// value = use the provided timestamp.
type NullableTimestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*NullableTimestamp_Value
	//	*NullableTimestamp_NullValue
	Kind          isNullableTimestamp_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableTimestamp) Reset() {
	*x = NullableTimestamp{}
	mi := &file_src_proto_sharing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableTimestamp) ProtoMessage() {}

func (x *NullableTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableTimestamp.ProtoReflect.Descriptor instead.
func (*NullableTimestamp) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{1}
}

func (x *NullableTimestamp) GetKind() isNullableTimestamp_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *NullableTimestamp) GetValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*NullableTimestamp_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *NullableTimestamp) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*NullableTimestamp_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

type isNullableTimestamp_Kind interface {
	isNullableTimestamp_Kind()
}

type NullableTimestamp_Value struct {
	Value *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type NullableTimestamp_NullValue struct {
	NullValue bool `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,oneof"`
}

func (*NullableTimestamp_Value) isNullableTimestamp_Kind() {}

func (*NullableTimestamp_NullValue) isNullableTimestamp_Kind() {}

// A persisted share entry for a note.
type NoteShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   *NullableString        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	NoteId        string                 `protobuf:"bytes,3,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	OnlineSince   *NullableTimestamp     `protobuf:"bytes,6,opt,name=online_since,json=onlineSince,proto3" json:"online_since,omitempty"`
	OnlineUntil   *NullableTimestamp     `protobuf:"bytes,7,opt,name=online_until,json=onlineUntil,proto3" json:"online_until,omitempty"`
	Permission    SharePermission        `protobuf:"varint,8,opt,name=permission,proto3,enum=proto.SharePermission" json:"permission,omitempty"`
	AccessAs      string                 `protobuf:"bytes,9,opt,name=access_as,json=accessAs,proto3" json:"access_as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteShare) Reset() {
	*x = NoteShare{}
	mi := &file_src_proto_sharing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteShare) ProtoMessage() {}

func (x *NoteShare) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteShare.ProtoReflect.Descriptor instead.
func (*NoteShare) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{2}
}

func (x *NoteShare) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoteShare) GetDescription() *NullableString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *NoteShare) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteShare) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NoteShare) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *NoteShare) GetOnlineSince() *NullableTimestamp {
	if x != nil {
		return x.OnlineSince
	}
	return nil
}

func (x *NoteShare) GetOnlineUntil() *NullableTimestamp {
	if x != nil {
		return x.OnlineUntil
	}
	return nil
}

func (x *NoteShare) GetPermission() SharePermission {
	if x != nil {
		return x.Permission
	}
	return SharePermission_SHARE_PERMISSION_UNSPECIFIED
}

func (x *NoteShare) GetAccessAs() string {
	if x != nil {
		return x.AccessAs
	}
	return ""
}

// Filter for shares. Dates are inclusive:
// online_since.value matches online_since >= value, online_until.value matches
// online_until <= value, null_value matches rows where the column is NULL.
type ShareFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        *string                `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3,oneof" json:"note_id,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	OnlineSince   *NullableTimestamp     `protobuf:"bytes,3,opt,name=online_since,json=onlineSince,proto3" json:"online_since,omitempty"`
	OnlineUntil   *NullableTimestamp     `protobuf:"bytes,4,opt,name=online_until,json=onlineUntil,proto3" json:"online_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFilter) Reset() {
	*x = ShareFilter{}
	mi := &file_src_proto_sharing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFilter) ProtoMessage() {}

func (x *ShareFilter) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFilter.ProtoReflect.Descriptor instead.
func (*ShareFilter) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{3}
}

func (x *ShareFilter) GetNoteId() string {
	if x != nil && x.NoteId != nil {
		return *x.NoteId
	}
	return ""
}

func (x *ShareFilter) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *ShareFilter) GetOnlineSince() *NullableTimestamp {
	if x != nil {
		return x.OnlineSince
	}
	return nil
}

func (x *ShareFilter) GetOnlineUntil() *NullableTimestamp {
	if x != nil {
		return x.OnlineUntil
	}
	return nil
}

// Create one share. The requester user_id is used for permission checks.
type CreateShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description   *NullableString        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	NoteId        string                 `protobuf:"bytes,3,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	OnlineSince   *NullableTimestamp     `protobuf:"bytes,4,opt,name=online_since,json=onlineSince,proto3" json:"online_since,omitempty"`
	OnlineUntil   *NullableTimestamp     `protobuf:"bytes,5,opt,name=online_until,json=onlineUntil,proto3" json:"online_until,omitempty"`
	Permission    SharePermission        `protobuf:"varint,6,opt,name=permission,proto3,enum=proto.SharePermission" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareRequest) Reset() {
	*x = CreateShareRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareRequest) ProtoMessage() {}

func (x *CreateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareRequest.ProtoReflect.Descriptor instead.
func (*CreateShareRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShareRequest) GetDescription() *NullableString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateShareRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *CreateShareRequest) GetOnlineSince() *NullableTimestamp {
	if x != nil {
		return x.OnlineSince
	}
	return nil
}

func (x *CreateShareRequest) GetOnlineUntil() *NullableTimestamp {
	if x != nil {
		return x.OnlineUntil
	}
	return nil
}

func (x *CreateShareRequest) GetPermission() SharePermission {
	if x != nil {
		return x.Permission
	}
	return SharePermission_SHARE_PERMISSION_UNSPECIFIED
}

// Access a share by its ID (the share_id segment of /public/n/<share_id>).
type AccessShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessShareRequest) Reset() {
	*x = AccessShareRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessShareRequest) ProtoMessage() {}

func (x *AccessShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessShareRequest.ProtoReflect.Descriptor instead.
func (*AccessShareRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{5}
}

func (x *AccessShareRequest) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

// Response for an access share request, containing the note associated with the share
type AccessShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *NoteShare             `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessShareResponse) Reset() {
	*x = AccessShareResponse{}
	mi := &file_src_proto_sharing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessShareResponse) ProtoMessage() {}

func (x *AccessShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessShareResponse.ProtoReflect.Descriptor instead.
func (*AccessShareResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{6}
}

func (x *AccessShareResponse) GetShare() *NoteShare {
	if x != nil {
		return x.Share
	}
	return nil
}

// Look up the temporary user id used to access a share.
type GetShareUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareUserRequest) Reset() {
	*x = GetShareUserRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareUserRequest) ProtoMessage() {}

func (x *GetShareUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareUserRequest.ProtoReflect.Descriptor instead.
func (*GetShareUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{7}
}

func (x *GetShareUserRequest) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

// Response carrying the temporary user id for a share.
type GetShareUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessAs      string                 `protobuf:"bytes,1,opt,name=access_as,json=accessAs,proto3" json:"access_as,omitempty"`
	OnlineUntil   *NullableTimestamp     `protobuf:"bytes,2,opt,name=online_until,json=onlineUntil,proto3" json:"online_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareUserResponse) Reset() {
	*x = GetShareUserResponse{}
	mi := &file_src_proto_sharing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareUserResponse) ProtoMessage() {}

func (x *GetShareUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareUserResponse.ProtoReflect.Descriptor instead.
func (*GetShareUserResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{8}
}

func (x *GetShareUserResponse) GetAccessAs() string {
	if x != nil {
		return x.AccessAs
	}
	return ""
}

func (x *GetShareUserResponse) GetOnlineUntil() *NullableTimestamp {
	if x != nil {
		return x.OnlineUntil
	}
	return nil
}

// Update one share. Only fields present on share should be updated.
// The requester user_id is used for permission checks.
type UpdateShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Share         *NoteShare             `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareRequest) Reset() {
	*x = UpdateShareRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareRequest) ProtoMessage() {}

func (x *UpdateShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareRequest.ProtoReflect.Descriptor instead.
func (*UpdateShareRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateShareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateShareRequest) GetShare() *NoteShare {
	if x != nil {
		return x.Share
	}
	return nil
}

// Fetch shares by their exact share IDs.
// The requester user_id is used for permission checks.
type GetSharesByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShareIds      []string               `protobuf:"bytes,2,rep,name=share_ids,json=shareIds,proto3" json:"share_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharesByIdRequest) Reset() {
	*x = GetSharesByIdRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharesByIdRequest) ProtoMessage() {}

func (x *GetSharesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharesByIdRequest.ProtoReflect.Descriptor instead.
func (*GetSharesByIdRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{10}
}

func (x *GetSharesByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSharesByIdRequest) GetShareIds() []string {
	if x != nil {
		return x.ShareIds
	}
	return nil
}

// Fetch shares matching a filter.
// The requester user_id is used for permission checks.
type GetSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filter        *ShareFilter           `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharesRequest) Reset() {
	*x = GetSharesRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharesRequest) ProtoMessage() {}

func (x *GetSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharesRequest.ProtoReflect.Descriptor instead.
func (*GetSharesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{11}
}

func (x *GetSharesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSharesRequest) GetFilter() *ShareFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Delete shares by their exact share IDs.
// The requester user_id is used for permission checks.
type DeleteSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShareIds      []string               `protobuf:"bytes,2,rep,name=share_ids,json=shareIds,proto3" json:"share_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSharesRequest) Reset() {
	*x = DeleteSharesRequest{}
	mi := &file_src_proto_sharing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSharesRequest) ProtoMessage() {}

func (x *DeleteSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_sharing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSharesRequest.ProtoReflect.Descriptor instead.
func (*DeleteSharesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_sharing_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSharesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteSharesRequest) GetShareIds() []string {
	if x != nil {
		return x.ShareIds
	}
	return nil
}

var File_src_proto_sharing_proto protoreflect.FileDescriptor

const file_src_proto_sharing_proto_rawDesc = "" +
	"\n" +
	"\x17src/proto/sharing.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x0eNullableString\x12\x16\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x12\x1f\n" +
	"\n" +
	"null_value\x18\x02 \x01(\bH\x00R\tnullValueB\x06\n" +
	"\x04kind\"p\n" +
	"\x11NullableTimestamp\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05value\x12\x1f\n" +
	"\n" +
	"null_value\x18\x02 \x01(\bH\x00R\tnullValueB\x06\n" +
	"\x04kind\"\x96\x03\n" +
	"\tNoteShare\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\vdescription\x18\x02 \x01(\v2\x15.proto.NullableStringR\vdescription\x12\x17\n" +
	"\anote_id\x18\x03 \x01(\tR\x06noteId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12;\n" +
	"\fonline_since\x18\x06 \x01(\v2\x18.proto.NullableTimestampR\vonlineSince\x12;\n" +
	"\fonline_until\x18\a \x01(\v2\x18.proto.NullableTimestampR\vonlineUntil\x126\n" +
	"\n" +
	"permission\x18\b \x01(\x0e2\x16.proto.SharePermissionR\n" +
	"permission\x12\x1b\n" +
	"\taccess_as\x18\t \x01(\tR\baccessAs\"\xe4\x01\n" +
	"\vShareFilter\x12\x1c\n" +
	"\anote_id\x18\x01 \x01(\tH\x00R\x06noteId\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x12;\n" +
	"\fonline_since\x18\x03 \x01(\v2\x18.proto.NullableTimestampR\vonlineSince\x12;\n" +
	"\fonline_until\x18\x04 \x01(\v2\x18.proto.NullableTimestampR\vonlineUntilB\n" +
	"\n" +
	"\b_note_idB\r\n" +
	"\v_created_by\"\xb1\x02\n" +
	"\x12CreateShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\vdescription\x18\x02 \x01(\v2\x15.proto.NullableStringR\vdescription\x12\x17\n" +
	"\anote_id\x18\x03 \x01(\tR\x06noteId\x12;\n" +
	"\fonline_since\x18\x04 \x01(\v2\x18.proto.NullableTimestampR\vonlineSince\x12;\n" +
	"\fonline_until\x18\x05 \x01(\v2\x18.proto.NullableTimestampR\vonlineUntil\x126\n" +
	"\n" +
	"permission\x18\x06 \x01(\x0e2\x16.proto.SharePermissionR\n" +
	"permission\"/\n" +
	"\x12AccessShareRequest\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\"=\n" +
	"\x13AccessShareResponse\x12&\n" +
	"\x05share\x18\x01 \x01(\v2\x10.proto.NoteShareR\x05share\"0\n" +
	"\x13GetShareUserRequest\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\"p\n" +
	"\x14GetShareUserResponse\x12\x1b\n" +
	"\taccess_as\x18\x01 \x01(\tR\baccessAs\x12;\n" +
	"\fonline_until\x18\x02 \x01(\v2\x18.proto.NullableTimestampR\vonlineUntil\"U\n" +
	"\x12UpdateShareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x05share\x18\x02 \x01(\v2\x10.proto.NoteShareR\x05share\"L\n" +
	"\x14GetSharesByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tshare_ids\x18\x02 \x03(\tR\bshareIds\"W\n" +
	"\x10GetSharesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06filter\x18\x02 \x01(\v2\x12.proto.ShareFilterR\x06filter\"K\n" +
	"\x13DeleteSharesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tshare_ids\x18\x02 \x03(\tR\bshareIds*j\n" +
	"\x0fSharePermission\x12 \n" +
	"\x1cSHARE_PERMISSION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SHARE_PERMISSION_READ\x10\x01\x12\x1a\n" +
	"\x16SHARE_PERMISSION_WRITE\x10\x022\xd7\x03\n" +
	"\x0eSharingService\x12:\n" +
	"\vCreateShare\x12\x19.proto.CreateShareRequest\x1a\x10.proto.NoteShare\x12:\n" +
	"\vUpdateShare\x12\x19.proto.UpdateShareRequest\x1a\x10.proto.NoteShare\x12@\n" +
	"\rGetSharesById\x12\x1b.proto.GetSharesByIdRequest\x1a\x10.proto.NoteShare0\x01\x128\n" +
	"\tGetShares\x12\x17.proto.GetSharesRequest\x1a\x10.proto.NoteShare0\x01\x12B\n" +
	"\fDeleteShares\x12\x1a.proto.DeleteSharesRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\vAccessShare\x12\x19.proto.AccessShareRequest\x1a\x1a.proto.AccessShareResponse\x12G\n" +
	"\fGetShareUser\x12\x1a.proto.GetShareUserRequest\x1a\x1b.proto.GetShareUserResponseB1Z/github.com/KuramaSyu/Wersu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_sharing_proto_rawDescOnce sync.Once
	file_src_proto_sharing_proto_rawDescData []byte
)

func file_src_proto_sharing_proto_rawDescGZIP() []byte {
	file_src_proto_sharing_proto_rawDescOnce.Do(func() {
		file_src_proto_sharing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_sharing_proto_rawDesc), len(file_src_proto_sharing_proto_rawDesc)))
	})
	return file_src_proto_sharing_proto_rawDescData
}

var file_src_proto_sharing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_sharing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_src_proto_sharing_proto_goTypes = []any{
	(SharePermission)(0),          // 0: proto.SharePermission
	(*NullableString)(nil),        // 1: proto.NullableString
	(*NullableTimestamp)(nil),     // 2: proto.NullableTimestamp
	(*NoteShare)(nil),             // 3: proto.NoteShare
	(*ShareFilter)(nil),           // 4: proto.ShareFilter
	(*CreateShareRequest)(nil),    // 5: proto.CreateShareRequest
	(*AccessShareRequest)(nil),    // 6: proto.AccessShareRequest
	(*AccessShareResponse)(nil),   // 7: proto.AccessShareResponse
	(*GetShareUserRequest)(nil),   // 8: proto.GetShareUserRequest
	(*GetShareUserResponse)(nil),  // 9: proto.GetShareUserResponse
	(*UpdateShareRequest)(nil),    // 10: proto.UpdateShareRequest
	(*GetSharesByIdRequest)(nil),  // 11: proto.GetSharesByIdRequest
	(*GetSharesRequest)(nil),      // 12: proto.GetSharesRequest
	(*DeleteSharesRequest)(nil),   // 13: proto.DeleteSharesRequest
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_src_proto_sharing_proto_depIdxs = []int32{
	14, // 0: proto.NullableTimestamp.value:type_name -> google.protobuf.Timestamp
	1,  // 1: proto.NoteShare.description:type_name -> proto.NullableString
	14, // 2: proto.NoteShare.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: proto.NoteShare.online_since:type_name -> proto.NullableTimestamp
	2,  // 4: proto.NoteShare.online_until:type_name -> proto.NullableTimestamp
	0,  // 5: proto.NoteShare.permission:type_name -> proto.SharePermission
	2,  // 6: proto.ShareFilter.online_since:type_name -> proto.NullableTimestamp
	2,  // 7: proto.ShareFilter.online_until:type_name -> proto.NullableTimestamp
	1,  // 8: proto.CreateShareRequest.description:type_name -> proto.NullableString
	2,  // 9: proto.CreateShareRequest.online_since:type_name -> proto.NullableTimestamp
	2,  // 10: proto.CreateShareRequest.online_until:type_name -> proto.NullableTimestamp
	0,  // 11: proto.CreateShareRequest.permission:type_name -> proto.SharePermission
	3,  // 12: proto.AccessShareResponse.share:type_name -> proto.NoteShare
	2,  // 13: proto.GetShareUserResponse.online_until:type_name -> proto.NullableTimestamp
	3,  // 14: proto.UpdateShareRequest.share:type_name -> proto.NoteShare
	4,  // 15: proto.GetSharesRequest.filter:type_name -> proto.ShareFilter
	5,  // 16: proto.SharingService.CreateShare:input_type -> proto.CreateShareRequest
	10, // 17: proto.SharingService.UpdateShare:input_type -> proto.UpdateShareRequest
	11, // 18: proto.SharingService.GetSharesById:input_type -> proto.GetSharesByIdRequest
	12, // 19: proto.SharingService.GetShares:input_type -> proto.GetSharesRequest
	13, // 20: proto.SharingService.DeleteShares:input_type -> proto.DeleteSharesRequest
	6,  // 21: proto.SharingService.AccessShare:input_type -> proto.AccessShareRequest
	8,  // 22: proto.SharingService.GetShareUser:input_type -> proto.GetShareUserRequest
	3,  // 23: proto.SharingService.CreateShare:output_type -> proto.NoteShare
	3,  // 24: proto.SharingService.UpdateShare:output_type -> proto.NoteShare
	3,  // 25: proto.SharingService.GetSharesById:output_type -> proto.NoteShare
	3,  // 26: proto.SharingService.GetShares:output_type -> proto.NoteShare
	15, // 27: proto.SharingService.DeleteShares:output_type -> google.protobuf.Empty
	7,  // 28: proto.SharingService.AccessShare:output_type -> proto.AccessShareResponse
	9,  // 29: proto.SharingService.GetShareUser:output_type -> proto.GetShareUserResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_src_proto_sharing_proto_init() }
func file_src_proto_sharing_proto_init() {
	if File_src_proto_sharing_proto != nil {
		return
	}
	file_src_proto_sharing_proto_msgTypes[0].OneofWrappers = []any{
		(*NullableString_Value)(nil),
		(*NullableString_NullValue)(nil),
	}
	file_src_proto_sharing_proto_msgTypes[1].OneofWrappers = []any{
		(*NullableTimestamp_Value)(nil),
		(*NullableTimestamp_NullValue)(nil),
	}
	file_src_proto_sharing_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_sharing_proto_rawDesc), len(file_src_proto_sharing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_sharing_proto_goTypes,
		DependencyIndexes: file_src_proto_sharing_proto_depIdxs,
		EnumInfos:         file_src_proto_sharing_proto_enumTypes,
		MessageInfos:      file_src_proto_sharing_proto_msgTypes,
	}.Build()
	File_src_proto_sharing_proto = out.File
	file_src_proto_sharing_proto_goTypes = nil
	file_src_proto_sharing_proto_depIdxs = nil
}
