// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: src/proto/sharing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SharingService_CreateShare_FullMethodName   = "/proto.SharingService/CreateShare"
	SharingService_UpdateShare_FullMethodName   = "/proto.SharingService/UpdateShare"
	SharingService_GetSharesById_FullMethodName = "/proto.SharingService/GetSharesById"
	SharingService_GetShares_FullMethodName     = "/proto.SharingService/GetShares"
	SharingService_DeleteShares_FullMethodName  = "/proto.SharingService/DeleteShares"
)

// SharingServiceClient is the client API for SharingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharingServiceClient interface {
	CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*NoteShare, error)
	UpdateShare(ctx context.Context, in *UpdateShareRequest, opts ...grpc.CallOption) (*NoteShare, error)
	GetSharesById(ctx context.Context, in *GetSharesByIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteShare], error)
	GetShares(ctx context.Context, in *GetSharesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteShare], error)
	DeleteShares(ctx context.Context, in *DeleteSharesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sharingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSharingServiceClient(cc grpc.ClientConnInterface) SharingServiceClient {
	return &sharingServiceClient{cc}
}

func (c *sharingServiceClient) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*NoteShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteShare)
	err := c.cc.Invoke(ctx, SharingService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) UpdateShare(ctx context.Context, in *UpdateShareRequest, opts ...grpc.CallOption) (*NoteShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteShare)
	err := c.cc.Invoke(ctx, SharingService_UpdateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) GetSharesById(ctx context.Context, in *GetSharesByIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteShare], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SharingService_ServiceDesc.Streams[0], SharingService_GetSharesById_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSharesByIdRequest, NoteShare]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SharingService_GetSharesByIdClient = grpc.ServerStreamingClient[NoteShare]

func (c *sharingServiceClient) GetShares(ctx context.Context, in *GetSharesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NoteShare], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SharingService_ServiceDesc.Streams[1], SharingService_GetShares_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSharesRequest, NoteShare]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SharingService_GetSharesClient = grpc.ServerStreamingClient[NoteShare]

func (c *sharingServiceClient) DeleteShares(ctx context.Context, in *DeleteSharesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SharingService_DeleteShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharingServiceServer is the server API for SharingService service.
// All implementations must embed UnimplementedSharingServiceServer
// for forward compatibility.
type SharingServiceServer interface {
	CreateShare(context.Context, *CreateShareRequest) (*NoteShare, error)
	UpdateShare(context.Context, *UpdateShareRequest) (*NoteShare, error)
	GetSharesById(*GetSharesByIdRequest, grpc.ServerStreamingServer[NoteShare]) error
	GetShares(*GetSharesRequest, grpc.ServerStreamingServer[NoteShare]) error
	DeleteShares(context.Context, *DeleteSharesRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSharingServiceServer()
}

// UnimplementedSharingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharingServiceServer struct{}

func (UnimplementedSharingServiceServer) CreateShare(context.Context, *CreateShareRequest) (*NoteShare, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedSharingServiceServer) UpdateShare(context.Context, *UpdateShareRequest) (*NoteShare, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShare not implemented")
}
func (UnimplementedSharingServiceServer) GetSharesById(*GetSharesByIdRequest, grpc.ServerStreamingServer[NoteShare]) error {
	return status.Error(codes.Unimplemented, "method GetSharesById not implemented")
}
func (UnimplementedSharingServiceServer) GetShares(*GetSharesRequest, grpc.ServerStreamingServer[NoteShare]) error {
	return status.Error(codes.Unimplemented, "method GetShares not implemented")
}
func (UnimplementedSharingServiceServer) DeleteShares(context.Context, *DeleteSharesRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShares not implemented")
}
func (UnimplementedSharingServiceServer) mustEmbedUnimplementedSharingServiceServer() {}
func (UnimplementedSharingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSharingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharingServiceServer will
// result in compilation errors.
type UnsafeSharingServiceServer interface {
	mustEmbedUnimplementedSharingServiceServer()
}

func RegisterSharingServiceServer(s grpc.ServiceRegistrar, srv SharingServiceServer) {
	// If the following call panics, it indicates UnimplementedSharingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SharingService_ServiceDesc, srv)
}

func _SharingService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).CreateShare(ctx, req.(*CreateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_UpdateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).UpdateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_UpdateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).UpdateShare(ctx, req.(*UpdateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_GetSharesById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSharesByIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SharingServiceServer).GetSharesById(m, &grpc.GenericServerStream[GetSharesByIdRequest, NoteShare]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SharingService_GetSharesByIdServer = grpc.ServerStreamingServer[NoteShare]

func _SharingService_GetShares_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSharesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SharingServiceServer).GetShares(m, &grpc.GenericServerStream[GetSharesRequest, NoteShare]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SharingService_GetSharesServer = grpc.ServerStreamingServer[NoteShare]

func _SharingService_DeleteShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).DeleteShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_DeleteShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).DeleteShares(ctx, req.(*DeleteSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SharingService_ServiceDesc is the grpc.ServiceDesc for SharingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SharingService",
	HandlerType: (*SharingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShare",
			Handler:    _SharingService_CreateShare_Handler,
		},
		{
			MethodName: "UpdateShare",
			Handler:    _SharingService_UpdateShare_Handler,
		},
		{
			MethodName: "DeleteShares",
			Handler:    _SharingService_DeleteShares_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSharesById",
			Handler:       _SharingService_GetSharesById_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetShares",
			Handler:       _SharingService_GetShares_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/sharing.proto",
}
