// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: src/proto/shelf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap strategy the service should run immediately after
// inserting the shelf row.  “UNSPECIFIED“ / “NONE“ both mean
// "no strategy" -- the caller just gets the bare shelf.
//
// “ZETTELKASTEN“ runs the same flow the user bootstrap
// uses: create the three default books (fleeting / literature /
// permanent) and bind them to the shelf, then insert the
// “NoteCreated -> add_to_directory(fleeting)“ rule attached to
// the new shelf.  The strategy is idempotent: re-running it on a
// shelf that already carries books is a no-op.
type BootstrapStrategy int32

const (
	BootstrapStrategy_BOOTSTRAP_STRATEGY_UNSPECIFIED  BootstrapStrategy = 0
	BootstrapStrategy_BOOTSTRAP_STRATEGY_NONE         BootstrapStrategy = 1
	BootstrapStrategy_BOOTSTRAP_STRATEGY_ZETTELKASTEN BootstrapStrategy = 2
)

// Enum value maps for BootstrapStrategy.
var (
	BootstrapStrategy_name = map[int32]string{
		0: "BOOTSTRAP_STRATEGY_UNSPECIFIED",
		1: "BOOTSTRAP_STRATEGY_NONE",
		2: "BOOTSTRAP_STRATEGY_ZETTELKASTEN",
	}
	BootstrapStrategy_value = map[string]int32{
		"BOOTSTRAP_STRATEGY_UNSPECIFIED":  0,
		"BOOTSTRAP_STRATEGY_NONE":         1,
		"BOOTSTRAP_STRATEGY_ZETTELKASTEN": 2,
	}
)

func (x BootstrapStrategy) Enum() *BootstrapStrategy {
	p := new(BootstrapStrategy)
	*p = x
	return p
}

func (x BootstrapStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BootstrapStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_src_proto_shelf_proto_enumTypes[0].Descriptor()
}

func (BootstrapStrategy) Type() protoreflect.EnumType {
	return &file_src_proto_shelf_proto_enumTypes[0]
}

func (x BootstrapStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BootstrapStrategy.Descriptor instead.
func (BootstrapStrategy) EnumDescriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{0}
}

// A shelf is a flat (non-hierarchical) grouping of books
// (directories).  Mirrors the metadata columns of a
// :class:`~src.db.entities.directory.directory.DirectoryEntity`
// minus the parent / child lists -- shelves don't nest.
//
// “book_ids“ is populated only when the caller opts in via
// “include_books=true“ on the read request; empty otherwise.
type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ReadmeNoteId  string                 `protobuf:"bytes,6,opt,name=readme_note_id,json=readmeNoteId,proto3" json:"readme_note_id,omitempty"`
	BookIds       []string               `protobuf:"bytes,7,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_src_proto_shelf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shelf) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Shelf) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Shelf) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Shelf) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Shelf) GetReadmeNoteId() string {
	if x != nil {
		return x.ReadmeNoteId
	}
	return ""
}

func (x *Shelf) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

// What the strategy produced.  Echoed back on
// :class:`CreateShelfResponse` so callers can confirm what was
// created.  Empty when no strategy ran.
type BootstrapResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreatedDirectoryIds []string               `protobuf:"bytes,1,rep,name=created_directory_ids,json=createdDirectoryIds,proto3" json:"created_directory_ids,omitempty"`
	CreatedRuleId       string                 `protobuf:"bytes,2,opt,name=created_rule_id,json=createdRuleId,proto3" json:"created_rule_id,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BootstrapResult) Reset() {
	*x = BootstrapResult{}
	mi := &file_src_proto_shelf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResult) ProtoMessage() {}

func (x *BootstrapResult) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResult.ProtoReflect.Descriptor instead.
func (*BootstrapResult) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapResult) GetCreatedDirectoryIds() []string {
	if x != nil {
		return x.CreatedDirectoryIds
	}
	return nil
}

func (x *BootstrapResult) GetCreatedRuleId() string {
	if x != nil {
		return x.CreatedRuleId
	}
	return ""
}

func (x *BootstrapResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Returned by “DeleteShelf“ when “dry=true“.  The fields
// describe the would-be-cascade so the UI can show a
// confirmation before issuing the real delete.  Empty when
// “dry=false“ and the delete succeeded.
type DeleteShelfResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Dry             bool                   `protobuf:"varint,1,opt,name=dry,proto3" json:"dry,omitempty"`
	AffectedBookIds []string               `protobuf:"bytes,2,rep,name=affected_book_ids,json=affectedBookIds,proto3" json:"affected_book_ids,omitempty"`
	BindingCount    int32                  `protobuf:"varint,3,opt,name=binding_count,json=bindingCount,proto3" json:"binding_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteShelfResponse) Reset() {
	*x = DeleteShelfResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfResponse) ProtoMessage() {}

func (x *DeleteShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShelfResponse.ProtoReflect.Descriptor instead.
func (*DeleteShelfResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShelfResponse) GetDry() bool {
	if x != nil {
		return x.Dry
	}
	return false
}

func (x *DeleteShelfResponse) GetAffectedBookIds() []string {
	if x != nil {
		return x.AffectedBookIds
	}
	return nil
}

func (x *DeleteShelfResponse) GetBindingCount() int32 {
	if x != nil {
		return x.BindingCount
	}
	return 0
}

type GetShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IncludeBooks  bool                   `protobuf:"varint,3,opt,name=include_books,json=includeBooks,proto3" json:"include_books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfRequest.ProtoReflect.Descriptor instead.
func (*GetShelfRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{3}
}

func (x *GetShelfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetShelfRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetShelfRequest) GetIncludeBooks() bool {
	if x != nil {
		return x.IncludeBooks
	}
	return false
}

type GetShelvesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	IncludeBooks  bool                   `protobuf:"varint,3,opt,name=include_books,json=includeBooks,proto3" json:"include_books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelvesRequest) Reset() {
	*x = GetShelvesRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelvesRequest) ProtoMessage() {}

func (x *GetShelvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelvesRequest.ProtoReflect.Descriptor instead.
func (*GetShelvesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{4}
}

func (x *GetShelvesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetShelvesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetShelvesRequest) GetIncludeBooks() bool {
	if x != nil {
		return x.IncludeBooks
	}
	return false
}

type ListShelvesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeBooks  bool                   `protobuf:"varint,4,opt,name=include_books,json=includeBooks,proto3" json:"include_books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesRequest) Reset() {
	*x = ListShelvesRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesRequest) ProtoMessage() {}

func (x *ListShelvesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesRequest.ProtoReflect.Descriptor instead.
func (*ListShelvesRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{5}
}

func (x *ListShelvesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListShelvesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListShelvesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListShelvesRequest) GetIncludeBooks() bool {
	if x != nil {
		return x.IncludeBooks
	}
	return false
}

type CreateShelfRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Slug              string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	DisplayName       *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description       *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl          *string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	ReadmeNoteId      *string                `protobuf:"bytes,6,opt,name=readme_note_id,json=readmeNoteId,proto3,oneof" json:"readme_note_id,omitempty"`
	BootstrapStrategy BootstrapStrategy      `protobuf:"varint,7,opt,name=bootstrap_strategy,json=bootstrapStrategy,proto3,enum=proto.BootstrapStrategy" json:"bootstrap_strategy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{6}
}

func (x *CreateShelfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShelfRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateShelfRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CreateShelfRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateShelfRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *CreateShelfRequest) GetReadmeNoteId() string {
	if x != nil && x.ReadmeNoteId != nil {
		return *x.ReadmeNoteId
	}
	return ""
}

func (x *CreateShelfRequest) GetBootstrapStrategy() BootstrapStrategy {
	if x != nil {
		return x.BootstrapStrategy
	}
	return BootstrapStrategy_BOOTSTRAP_STRATEGY_UNSPECIFIED
}

type UpdateShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	DisplayName   *string                `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	ReadmeNoteId  *string                `protobuf:"bytes,7,opt,name=readme_note_id,json=readmeNoteId,proto3,oneof" json:"readme_note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShelfRequest) Reset() {
	*x = UpdateShelfRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShelfRequest) ProtoMessage() {}

func (x *UpdateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShelfRequest.ProtoReflect.Descriptor instead.
func (*UpdateShelfRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateShelfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateShelfRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateShelfRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateShelfRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateShelfRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateShelfRequest) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *UpdateShelfRequest) GetReadmeNoteId() string {
	if x != nil && x.ReadmeNoteId != nil {
		return *x.ReadmeNoteId
	}
	return ""
}

type DeleteShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Dry           bool                   `protobuf:"varint,3,opt,name=dry,proto3" json:"dry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShelfRequest) Reset() {
	*x = DeleteShelfRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfRequest) ProtoMessage() {}

func (x *DeleteShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShelfRequest.ProtoReflect.Descriptor instead.
func (*DeleteShelfRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteShelfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteShelfRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteShelfRequest) GetDry() bool {
	if x != nil {
		return x.Dry
	}
	return false
}

type SetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	BookIds       []string               `protobuf:"bytes,3,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBooksRequest) Reset() {
	*x = SetBooksRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBooksRequest) ProtoMessage() {}

func (x *SetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBooksRequest.ProtoReflect.Descriptor instead.
func (*SetBooksRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{9}
}

func (x *SetBooksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetBooksRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *SetBooksRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type AttachBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	BookId        string                 `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachBookRequest) Reset() {
	*x = AttachBookRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBookRequest) ProtoMessage() {}

func (x *AttachBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBookRequest.ProtoReflect.Descriptor instead.
func (*AttachBookRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{10}
}

func (x *AttachBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttachBookRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *AttachBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type DetachBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	BookId        string                 `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachBookRequest) Reset() {
	*x = DetachBookRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBookRequest) ProtoMessage() {}

func (x *DetachBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBookRequest.ProtoReflect.Descriptor instead.
func (*DetachBookRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{11}
}

func (x *DetachBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DetachBookRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *DetachBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetBooksOfShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksOfShelfRequest) Reset() {
	*x = GetBooksOfShelfRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksOfShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksOfShelfRequest) ProtoMessage() {}

func (x *GetBooksOfShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksOfShelfRequest.ProtoReflect.Descriptor instead.
func (*GetBooksOfShelfRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{12}
}

func (x *GetBooksOfShelfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBooksOfShelfRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

type GetShelvesOfBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelvesOfBookRequest) Reset() {
	*x = GetShelvesOfBookRequest{}
	mi := &file_src_proto_shelf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelvesOfBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelvesOfBookRequest) ProtoMessage() {}

func (x *GetShelvesOfBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelvesOfBookRequest.ProtoReflect.Descriptor instead.
func (*GetShelvesOfBookRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{13}
}

func (x *GetShelvesOfBookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetShelvesOfBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelfResponse) Reset() {
	*x = ShelfResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelfResponse) ProtoMessage() {}

func (x *ShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelfResponse.ProtoReflect.Descriptor instead.
func (*ShelfResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{14}
}

func (x *ShelfResponse) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

type ShelvesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelves       []*Shelf               `protobuf:"bytes,1,rep,name=shelves,proto3" json:"shelves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelvesResponse) Reset() {
	*x = ShelvesResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelvesResponse) ProtoMessage() {}

func (x *ShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelvesResponse.ProtoReflect.Descriptor instead.
func (*ShelvesResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{15}
}

func (x *ShelvesResponse) GetShelves() []*Shelf {
	if x != nil {
		return x.Shelves
	}
	return nil
}

type CreateShelfResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Shelf           *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	BootstrapResult *BootstrapResult       `protobuf:"bytes,2,opt,name=bootstrap_result,json=bootstrapResult,proto3" json:"bootstrap_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateShelfResponse) Reset() {
	*x = CreateShelfResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfResponse) ProtoMessage() {}

func (x *CreateShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfResponse.ProtoReflect.Descriptor instead.
func (*CreateShelfResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{16}
}

func (x *CreateShelfResponse) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

func (x *CreateShelfResponse) GetBootstrapResult() *BootstrapResult {
	if x != nil {
		return x.BootstrapResult
	}
	return nil
}

type BooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookIds       []string               `protobuf:"bytes,1,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksResponse) Reset() {
	*x = BooksResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksResponse) ProtoMessage() {}

func (x *BooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksResponse.ProtoReflect.Descriptor instead.
func (*BooksResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{17}
}

func (x *BooksResponse) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type ShelfIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfIds      []string               `protobuf:"bytes,1,rep,name=shelf_ids,json=shelfIds,proto3" json:"shelf_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShelfIdsResponse) Reset() {
	*x = ShelfIdsResponse{}
	mi := &file_src_proto_shelf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShelfIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShelfIdsResponse) ProtoMessage() {}

func (x *ShelfIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shelf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShelfIdsResponse.ProtoReflect.Descriptor instead.
func (*ShelfIdsResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_shelf_proto_rawDescGZIP(), []int{18}
}

func (x *ShelfIdsResponse) GetShelfIds() []string {
	if x != nil {
		return x.ShelfIds
	}
	return nil
}

var File_src_proto_shelf_proto protoreflect.FileDescriptor

const file_src_proto_shelf_proto_rawDesc = "" +
	"\n" +
	"\x15src/proto/shelf.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xce\x01\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12$\n" +
	"\x0ereadme_note_id\x18\x06 \x01(\tR\freadmeNoteId\x12\x19\n" +
	"\bbook_ids\x18\a \x03(\tR\abookIds\"\x8f\x01\n" +
	"\x0fBootstrapResult\x122\n" +
	"\x15created_directory_ids\x18\x01 \x03(\tR\x13createdDirectoryIds\x12&\n" +
	"\x0fcreated_rule_id\x18\x02 \x01(\tR\rcreatedRuleId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"x\n" +
	"\x13DeleteShelfResponse\x12\x10\n" +
	"\x03dry\x18\x01 \x01(\bR\x03dry\x12*\n" +
	"\x11affected_book_ids\x18\x02 \x03(\tR\x0faffectedBookIds\x12#\n" +
	"\rbinding_count\x18\x03 \x01(\x05R\fbindingCount\"_\n" +
	"\x0fGetShelfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12#\n" +
	"\rinclude_books\x18\x03 \x01(\bR\fincludeBooks\"c\n" +
	"\x11GetShelvesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12#\n" +
	"\rinclude_books\x18\x03 \x01(\bR\fincludeBooks\"\x9f\x01\n" +
	"\x12ListShelvesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12#\n" +
	"\rinclude_books\x18\x04 \x01(\bR\fincludeBooksB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"\xe8\x02\n" +
	"\x12CreateShelfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x02R\bimageUrl\x88\x01\x01\x12)\n" +
	"\x0ereadme_note_id\x18\x06 \x01(\tH\x03R\freadmeNoteId\x88\x01\x01\x12G\n" +
	"\x12bootstrap_strategy\x18\a \x01(\x0e2\x18.proto.BootstrapStrategyR\x11bootstrapStrategyB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\x11\n" +
	"\x0f_readme_note_id\"\xbd\x02\n" +
	"\x12UpdateShelfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x00R\x04slug\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x04 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x06 \x01(\tH\x03R\bimageUrl\x88\x01\x01\x12)\n" +
	"\x0ereadme_note_id\x18\a \x01(\tH\x04R\freadmeNoteId\x88\x01\x01B\a\n" +
	"\x05_slugB\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_urlB\x11\n" +
	"\x0f_readme_note_id\"O\n" +
	"\x12DeleteShelfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03dry\x18\x03 \x01(\bR\x03dry\"`\n" +
	"\x0fSetBooksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bshelf_id\x18\x02 \x01(\tR\ashelfId\x12\x19\n" +
	"\bbook_ids\x18\x03 \x03(\tR\abookIds\"`\n" +
	"\x11AttachBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bshelf_id\x18\x02 \x01(\tR\ashelfId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\"`\n" +
	"\x11DetachBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bshelf_id\x18\x02 \x01(\tR\ashelfId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\"L\n" +
	"\x16GetBooksOfShelfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bshelf_id\x18\x02 \x01(\tR\ashelfId\"K\n" +
	"\x17GetShelvesOfBookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"3\n" +
	"\rShelfResponse\x12\"\n" +
	"\x05shelf\x18\x01 \x01(\v2\f.proto.ShelfR\x05shelf\"9\n" +
	"\x0fShelvesResponse\x12&\n" +
	"\ashelves\x18\x01 \x03(\v2\f.proto.ShelfR\ashelves\"|\n" +
	"\x13CreateShelfResponse\x12\"\n" +
	"\x05shelf\x18\x01 \x01(\v2\f.proto.ShelfR\x05shelf\x12A\n" +
	"\x10bootstrap_result\x18\x02 \x01(\v2\x16.proto.BootstrapResultR\x0fbootstrapResult\"*\n" +
	"\rBooksResponse\x12\x19\n" +
	"\bbook_ids\x18\x01 \x03(\tR\abookIds\"/\n" +
	"\x10ShelfIdsResponse\x12\x1b\n" +
	"\tshelf_ids\x18\x01 \x03(\tR\bshelfIds*y\n" +
	"\x11BootstrapStrategy\x12\"\n" +
	"\x1eBOOTSTRAP_STRATEGY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BOOTSTRAP_STRATEGY_NONE\x10\x01\x12#\n" +
	"\x1fBOOTSTRAP_STRATEGY_ZETTELKASTEN\x10\x022\xe7\x05\n" +
	"\fShelfService\x128\n" +
	"\bGetShelf\x12\x16.proto.GetShelfRequest\x1a\x14.proto.ShelfResponse\x12>\n" +
	"\n" +
	"GetShelves\x12\x18.proto.GetShelvesRequest\x1a\x16.proto.ShelvesResponse\x12@\n" +
	"\vListShelves\x12\x19.proto.ListShelvesRequest\x1a\x16.proto.ShelvesResponse\x12D\n" +
	"\vCreateShelf\x12\x19.proto.CreateShelfRequest\x1a\x1a.proto.CreateShelfResponse\x12>\n" +
	"\vUpdateShelf\x12\x19.proto.UpdateShelfRequest\x1a\x14.proto.ShelfResponse\x12D\n" +
	"\vDeleteShelf\x12\x19.proto.DeleteShelfRequest\x1a\x1a.proto.DeleteShelfResponse\x12:\n" +
	"\bSetBooks\x12\x16.proto.SetBooksRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"AttachBook\x12\x18.proto.AttachBookRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"DetachBook\x12\x18.proto.DetachBookRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0fGetBooksOfShelf\x12\x1d.proto.GetBooksOfShelfRequest\x1a\x14.proto.BooksResponse\x12K\n" +
	"\x10GetShelvesOfBook\x12\x1e.proto.GetShelvesOfBookRequest\x1a\x17.proto.ShelfIdsResponseB1Z/github.com/KuramaSyu/WerSu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_shelf_proto_rawDescOnce sync.Once
	file_src_proto_shelf_proto_rawDescData []byte
)

func file_src_proto_shelf_proto_rawDescGZIP() []byte {
	file_src_proto_shelf_proto_rawDescOnce.Do(func() {
		file_src_proto_shelf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_shelf_proto_rawDesc), len(file_src_proto_shelf_proto_rawDesc)))
	})
	return file_src_proto_shelf_proto_rawDescData
}

var file_src_proto_shelf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_proto_shelf_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_src_proto_shelf_proto_goTypes = []any{
	(BootstrapStrategy)(0),          // 0: proto.BootstrapStrategy
	(*Shelf)(nil),                   // 1: proto.Shelf
	(*BootstrapResult)(nil),         // 2: proto.BootstrapResult
	(*DeleteShelfResponse)(nil),     // 3: proto.DeleteShelfResponse
	(*GetShelfRequest)(nil),         // 4: proto.GetShelfRequest
	(*GetShelvesRequest)(nil),       // 5: proto.GetShelvesRequest
	(*ListShelvesRequest)(nil),      // 6: proto.ListShelvesRequest
	(*CreateShelfRequest)(nil),      // 7: proto.CreateShelfRequest
	(*UpdateShelfRequest)(nil),      // 8: proto.UpdateShelfRequest
	(*DeleteShelfRequest)(nil),      // 9: proto.DeleteShelfRequest
	(*SetBooksRequest)(nil),         // 10: proto.SetBooksRequest
	(*AttachBookRequest)(nil),       // 11: proto.AttachBookRequest
	(*DetachBookRequest)(nil),       // 12: proto.DetachBookRequest
	(*GetBooksOfShelfRequest)(nil),  // 13: proto.GetBooksOfShelfRequest
	(*GetShelvesOfBookRequest)(nil), // 14: proto.GetShelvesOfBookRequest
	(*ShelfResponse)(nil),           // 15: proto.ShelfResponse
	(*ShelvesResponse)(nil),         // 16: proto.ShelvesResponse
	(*CreateShelfResponse)(nil),     // 17: proto.CreateShelfResponse
	(*BooksResponse)(nil),           // 18: proto.BooksResponse
	(*ShelfIdsResponse)(nil),        // 19: proto.ShelfIdsResponse
	(*emptypb.Empty)(nil),           // 20: google.protobuf.Empty
}
var file_src_proto_shelf_proto_depIdxs = []int32{
	0,  // 0: proto.CreateShelfRequest.bootstrap_strategy:type_name -> proto.BootstrapStrategy
	1,  // 1: proto.ShelfResponse.shelf:type_name -> proto.Shelf
	1,  // 2: proto.ShelvesResponse.shelves:type_name -> proto.Shelf
	1,  // 3: proto.CreateShelfResponse.shelf:type_name -> proto.Shelf
	2,  // 4: proto.CreateShelfResponse.bootstrap_result:type_name -> proto.BootstrapResult
	4,  // 5: proto.ShelfService.GetShelf:input_type -> proto.GetShelfRequest
	5,  // 6: proto.ShelfService.GetShelves:input_type -> proto.GetShelvesRequest
	6,  // 7: proto.ShelfService.ListShelves:input_type -> proto.ListShelvesRequest
	7,  // 8: proto.ShelfService.CreateShelf:input_type -> proto.CreateShelfRequest
	8,  // 9: proto.ShelfService.UpdateShelf:input_type -> proto.UpdateShelfRequest
	9,  // 10: proto.ShelfService.DeleteShelf:input_type -> proto.DeleteShelfRequest
	10, // 11: proto.ShelfService.SetBooks:input_type -> proto.SetBooksRequest
	11, // 12: proto.ShelfService.AttachBook:input_type -> proto.AttachBookRequest
	12, // 13: proto.ShelfService.DetachBook:input_type -> proto.DetachBookRequest
	13, // 14: proto.ShelfService.GetBooksOfShelf:input_type -> proto.GetBooksOfShelfRequest
	14, // 15: proto.ShelfService.GetShelvesOfBook:input_type -> proto.GetShelvesOfBookRequest
	15, // 16: proto.ShelfService.GetShelf:output_type -> proto.ShelfResponse
	16, // 17: proto.ShelfService.GetShelves:output_type -> proto.ShelvesResponse
	16, // 18: proto.ShelfService.ListShelves:output_type -> proto.ShelvesResponse
	17, // 19: proto.ShelfService.CreateShelf:output_type -> proto.CreateShelfResponse
	15, // 20: proto.ShelfService.UpdateShelf:output_type -> proto.ShelfResponse
	3,  // 21: proto.ShelfService.DeleteShelf:output_type -> proto.DeleteShelfResponse
	20, // 22: proto.ShelfService.SetBooks:output_type -> google.protobuf.Empty
	20, // 23: proto.ShelfService.AttachBook:output_type -> google.protobuf.Empty
	20, // 24: proto.ShelfService.DetachBook:output_type -> google.protobuf.Empty
	18, // 25: proto.ShelfService.GetBooksOfShelf:output_type -> proto.BooksResponse
	19, // 26: proto.ShelfService.GetShelvesOfBook:output_type -> proto.ShelfIdsResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_src_proto_shelf_proto_init() }
func file_src_proto_shelf_proto_init() {
	if File_src_proto_shelf_proto != nil {
		return
	}
	file_src_proto_shelf_proto_msgTypes[5].OneofWrappers = []any{}
	file_src_proto_shelf_proto_msgTypes[6].OneofWrappers = []any{}
	file_src_proto_shelf_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_shelf_proto_rawDesc), len(file_src_proto_shelf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_shelf_proto_goTypes,
		DependencyIndexes: file_src_proto_shelf_proto_depIdxs,
		EnumInfos:         file_src_proto_shelf_proto_enumTypes,
		MessageInfos:      file_src_proto_shelf_proto_msgTypes,
	}.Build()
	File_src_proto_shelf_proto = out.File
	file_src_proto_shelf_proto_goTypes = nil
	file_src_proto_shelf_proto_depIdxs = nil
}
