// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: src/proto/shelf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShelfService_GetShelf_FullMethodName         = "/proto.ShelfService/GetShelf"
	ShelfService_GetShelves_FullMethodName       = "/proto.ShelfService/GetShelves"
	ShelfService_ListShelves_FullMethodName      = "/proto.ShelfService/ListShelves"
	ShelfService_CreateShelf_FullMethodName      = "/proto.ShelfService/CreateShelf"
	ShelfService_UpdateShelf_FullMethodName      = "/proto.ShelfService/UpdateShelf"
	ShelfService_DeleteShelf_FullMethodName      = "/proto.ShelfService/DeleteShelf"
	ShelfService_SetBooks_FullMethodName         = "/proto.ShelfService/SetBooks"
	ShelfService_AttachBook_FullMethodName       = "/proto.ShelfService/AttachBook"
	ShelfService_DetachBook_FullMethodName       = "/proto.ShelfService/DetachBook"
	ShelfService_GetBooksOfShelf_FullMethodName  = "/proto.ShelfService/GetBooksOfShelf"
	ShelfService_GetShelvesOfBook_FullMethodName = "/proto.ShelfService/GetShelvesOfBook"
)

// ShelfServiceClient is the client API for ShelfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShelfServiceClient interface {
	// CRUD
	GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*ShelfResponse, error)
	GetShelves(ctx context.Context, in *GetShelvesRequest, opts ...grpc.CallOption) (*ShelvesResponse, error)
	ListShelves(ctx context.Context, in *ListShelvesRequest, opts ...grpc.CallOption) (*ShelvesResponse, error)
	CreateShelf(ctx context.Context, in *CreateShelfRequest, opts ...grpc.CallOption) (*CreateShelfResponse, error)
	UpdateShelf(ctx context.Context, in *UpdateShelfRequest, opts ...grpc.CallOption) (*ShelfResponse, error)
	DeleteShelf(ctx context.Context, in *DeleteShelfRequest, opts ...grpc.CallOption) (*DeleteShelfResponse, error)
	// Book bindings
	SetBooks(ctx context.Context, in *SetBooksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AttachBook(ctx context.Context, in *AttachBookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DetachBook(ctx context.Context, in *DetachBookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBooksOfShelf(ctx context.Context, in *GetBooksOfShelfRequest, opts ...grpc.CallOption) (*BooksResponse, error)
	GetShelvesOfBook(ctx context.Context, in *GetShelvesOfBookRequest, opts ...grpc.CallOption) (*ShelfIdsResponse, error)
}

type shelfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShelfServiceClient(cc grpc.ClientConnInterface) ShelfServiceClient {
	return &shelfServiceClient{cc}
}

func (c *shelfServiceClient) GetShelf(ctx context.Context, in *GetShelfRequest, opts ...grpc.CallOption) (*ShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelfResponse)
	err := c.cc.Invoke(ctx, ShelfService_GetShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) GetShelves(ctx context.Context, in *GetShelvesRequest, opts ...grpc.CallOption) (*ShelvesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelvesResponse)
	err := c.cc.Invoke(ctx, ShelfService_GetShelves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) ListShelves(ctx context.Context, in *ListShelvesRequest, opts ...grpc.CallOption) (*ShelvesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelvesResponse)
	err := c.cc.Invoke(ctx, ShelfService_ListShelves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) CreateShelf(ctx context.Context, in *CreateShelfRequest, opts ...grpc.CallOption) (*CreateShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShelfResponse)
	err := c.cc.Invoke(ctx, ShelfService_CreateShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) UpdateShelf(ctx context.Context, in *UpdateShelfRequest, opts ...grpc.CallOption) (*ShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelfResponse)
	err := c.cc.Invoke(ctx, ShelfService_UpdateShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) DeleteShelf(ctx context.Context, in *DeleteShelfRequest, opts ...grpc.CallOption) (*DeleteShelfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShelfResponse)
	err := c.cc.Invoke(ctx, ShelfService_DeleteShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) SetBooks(ctx context.Context, in *SetBooksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShelfService_SetBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) AttachBook(ctx context.Context, in *AttachBookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShelfService_AttachBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) DetachBook(ctx context.Context, in *DetachBookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ShelfService_DetachBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) GetBooksOfShelf(ctx context.Context, in *GetBooksOfShelfRequest, opts ...grpc.CallOption) (*BooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooksResponse)
	err := c.cc.Invoke(ctx, ShelfService_GetBooksOfShelf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shelfServiceClient) GetShelvesOfBook(ctx context.Context, in *GetShelvesOfBookRequest, opts ...grpc.CallOption) (*ShelfIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShelfIdsResponse)
	err := c.cc.Invoke(ctx, ShelfService_GetShelvesOfBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShelfServiceServer is the server API for ShelfService service.
// All implementations must embed UnimplementedShelfServiceServer
// for forward compatibility.
type ShelfServiceServer interface {
	// CRUD
	GetShelf(context.Context, *GetShelfRequest) (*ShelfResponse, error)
	GetShelves(context.Context, *GetShelvesRequest) (*ShelvesResponse, error)
	ListShelves(context.Context, *ListShelvesRequest) (*ShelvesResponse, error)
	CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error)
	UpdateShelf(context.Context, *UpdateShelfRequest) (*ShelfResponse, error)
	DeleteShelf(context.Context, *DeleteShelfRequest) (*DeleteShelfResponse, error)
	// Book bindings
	SetBooks(context.Context, *SetBooksRequest) (*emptypb.Empty, error)
	AttachBook(context.Context, *AttachBookRequest) (*emptypb.Empty, error)
	DetachBook(context.Context, *DetachBookRequest) (*emptypb.Empty, error)
	GetBooksOfShelf(context.Context, *GetBooksOfShelfRequest) (*BooksResponse, error)
	GetShelvesOfBook(context.Context, *GetShelvesOfBookRequest) (*ShelfIdsResponse, error)
	mustEmbedUnimplementedShelfServiceServer()
}

// UnimplementedShelfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShelfServiceServer struct{}

func (UnimplementedShelfServiceServer) GetShelf(context.Context, *GetShelfRequest) (*ShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShelf not implemented")
}
func (UnimplementedShelfServiceServer) GetShelves(context.Context, *GetShelvesRequest) (*ShelvesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShelves not implemented")
}
func (UnimplementedShelfServiceServer) ListShelves(context.Context, *ListShelvesRequest) (*ShelvesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShelves not implemented")
}
func (UnimplementedShelfServiceServer) CreateShelf(context.Context, *CreateShelfRequest) (*CreateShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShelf not implemented")
}
func (UnimplementedShelfServiceServer) UpdateShelf(context.Context, *UpdateShelfRequest) (*ShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShelf not implemented")
}
func (UnimplementedShelfServiceServer) DeleteShelf(context.Context, *DeleteShelfRequest) (*DeleteShelfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShelf not implemented")
}
func (UnimplementedShelfServiceServer) SetBooks(context.Context, *SetBooksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBooks not implemented")
}
func (UnimplementedShelfServiceServer) AttachBook(context.Context, *AttachBookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachBook not implemented")
}
func (UnimplementedShelfServiceServer) DetachBook(context.Context, *DetachBookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachBook not implemented")
}
func (UnimplementedShelfServiceServer) GetBooksOfShelf(context.Context, *GetBooksOfShelfRequest) (*BooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBooksOfShelf not implemented")
}
func (UnimplementedShelfServiceServer) GetShelvesOfBook(context.Context, *GetShelvesOfBookRequest) (*ShelfIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShelvesOfBook not implemented")
}
func (UnimplementedShelfServiceServer) mustEmbedUnimplementedShelfServiceServer() {}
func (UnimplementedShelfServiceServer) testEmbeddedByValue()                      {}

// UnsafeShelfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShelfServiceServer will
// result in compilation errors.
type UnsafeShelfServiceServer interface {
	mustEmbedUnimplementedShelfServiceServer()
}

func RegisterShelfServiceServer(s grpc.ServiceRegistrar, srv ShelfServiceServer) {
	// If the following call panics, it indicates UnimplementedShelfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShelfService_ServiceDesc, srv)
}

func _ShelfService_GetShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).GetShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_GetShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).GetShelf(ctx, req.(*GetShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_GetShelves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).GetShelves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_GetShelves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).GetShelves(ctx, req.(*GetShelvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_ListShelves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShelvesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).ListShelves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_ListShelves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).ListShelves(ctx, req.(*ListShelvesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_CreateShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).CreateShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_CreateShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).CreateShelf(ctx, req.(*CreateShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_UpdateShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).UpdateShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_UpdateShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).UpdateShelf(ctx, req.(*UpdateShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_DeleteShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).DeleteShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_DeleteShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).DeleteShelf(ctx, req.(*DeleteShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_SetBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).SetBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_SetBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).SetBooks(ctx, req.(*SetBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_AttachBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).AttachBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_AttachBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).AttachBook(ctx, req.(*AttachBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_DetachBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).DetachBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_DetachBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).DetachBook(ctx, req.(*DetachBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_GetBooksOfShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksOfShelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).GetBooksOfShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_GetBooksOfShelf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).GetBooksOfShelf(ctx, req.(*GetBooksOfShelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShelfService_GetShelvesOfBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelvesOfBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShelfServiceServer).GetShelvesOfBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShelfService_GetShelvesOfBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShelfServiceServer).GetShelvesOfBook(ctx, req.(*GetShelvesOfBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShelfService_ServiceDesc is the grpc.ServiceDesc for ShelfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShelfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShelfService",
	HandlerType: (*ShelfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShelf",
			Handler:    _ShelfService_GetShelf_Handler,
		},
		{
			MethodName: "GetShelves",
			Handler:    _ShelfService_GetShelves_Handler,
		},
		{
			MethodName: "ListShelves",
			Handler:    _ShelfService_ListShelves_Handler,
		},
		{
			MethodName: "CreateShelf",
			Handler:    _ShelfService_CreateShelf_Handler,
		},
		{
			MethodName: "UpdateShelf",
			Handler:    _ShelfService_UpdateShelf_Handler,
		},
		{
			MethodName: "DeleteShelf",
			Handler:    _ShelfService_DeleteShelf_Handler,
		},
		{
			MethodName: "SetBooks",
			Handler:    _ShelfService_SetBooks_Handler,
		},
		{
			MethodName: "AttachBook",
			Handler:    _ShelfService_AttachBook_Handler,
		},
		{
			MethodName: "DetachBook",
			Handler:    _ShelfService_DetachBook_Handler,
		},
		{
			MethodName: "GetBooksOfShelf",
			Handler:    _ShelfService_GetBooksOfShelf_Handler,
		},
		{
			MethodName: "GetShelvesOfBook",
			Handler:    _ShelfService_GetShelvesOfBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/shelf.proto",
}
