// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: src/proto/thirdparty_migrations.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThirdpartyMigrationsService_BookstackBookImport_FullMethodName = "/proto.ThirdpartyMigrationsService/BookstackBookImport"
)

// ThirdpartyMigrationsServiceClient is the client API for ThirdpartyMigrationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Imports content from third-party documentation tools
// into the project's directory / note / attachment model.
// Only BookStack is implemented today; Notion, Confluence, ... will follow.
type ThirdpartyMigrationsServiceClient interface {
	BookstackBookImport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BookstackBookImportChunk, BookstackBookImportResponse], error)
}

type thirdpartyMigrationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdpartyMigrationsServiceClient(cc grpc.ClientConnInterface) ThirdpartyMigrationsServiceClient {
	return &thirdpartyMigrationsServiceClient{cc}
}

func (c *thirdpartyMigrationsServiceClient) BookstackBookImport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BookstackBookImportChunk, BookstackBookImportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ThirdpartyMigrationsService_ServiceDesc.Streams[0], ThirdpartyMigrationsService_BookstackBookImport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BookstackBookImportChunk, BookstackBookImportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThirdpartyMigrationsService_BookstackBookImportClient = grpc.ClientStreamingClient[BookstackBookImportChunk, BookstackBookImportResponse]

// ThirdpartyMigrationsServiceServer is the server API for ThirdpartyMigrationsService service.
// All implementations must embed UnimplementedThirdpartyMigrationsServiceServer
// for forward compatibility.
//
// Imports content from third-party documentation tools
// into the project's directory / note / attachment model.
// Only BookStack is implemented today; Notion, Confluence, ... will follow.
type ThirdpartyMigrationsServiceServer interface {
	BookstackBookImport(grpc.ClientStreamingServer[BookstackBookImportChunk, BookstackBookImportResponse]) error
	mustEmbedUnimplementedThirdpartyMigrationsServiceServer()
}

// UnimplementedThirdpartyMigrationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThirdpartyMigrationsServiceServer struct{}

func (UnimplementedThirdpartyMigrationsServiceServer) BookstackBookImport(grpc.ClientStreamingServer[BookstackBookImportChunk, BookstackBookImportResponse]) error {
	return status.Error(codes.Unimplemented, "method BookstackBookImport not implemented")
}
func (UnimplementedThirdpartyMigrationsServiceServer) mustEmbedUnimplementedThirdpartyMigrationsServiceServer() {
}
func (UnimplementedThirdpartyMigrationsServiceServer) testEmbeddedByValue() {}

// UnsafeThirdpartyMigrationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdpartyMigrationsServiceServer will
// result in compilation errors.
type UnsafeThirdpartyMigrationsServiceServer interface {
	mustEmbedUnimplementedThirdpartyMigrationsServiceServer()
}

func RegisterThirdpartyMigrationsServiceServer(s grpc.ServiceRegistrar, srv ThirdpartyMigrationsServiceServer) {
	// If the following call panics, it indicates UnimplementedThirdpartyMigrationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThirdpartyMigrationsService_ServiceDesc, srv)
}

func _ThirdpartyMigrationsService_BookstackBookImport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ThirdpartyMigrationsServiceServer).BookstackBookImport(&grpc.GenericServerStream[BookstackBookImportChunk, BookstackBookImportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThirdpartyMigrationsService_BookstackBookImportServer = grpc.ClientStreamingServer[BookstackBookImportChunk, BookstackBookImportResponse]

// ThirdpartyMigrationsService_ServiceDesc is the grpc.ServiceDesc for ThirdpartyMigrationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdpartyMigrationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ThirdpartyMigrationsService",
	HandlerType: (*ThirdpartyMigrationsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BookstackBookImport",
			Handler:       _ThirdpartyMigrationsService_BookstackBookImport_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/thirdparty_migrations.proto",
}
