// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: src/proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User Messages
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscordId     int64                  `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetDiscordId() int64 {
	if x != nil {
		return x.DiscordId
	}
	return 0
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	DiscordId     *int64                 `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3,oneof" json:"discord_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetUserRequest) GetDiscordId() int64 {
	if x != nil && x.DiscordId != nil {
		return *x.DiscordId
	}
	return 0
}

type PostUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscordId     int64                  `protobuf:"varint,1,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserRequest) Reset() {
	*x = PostUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserRequest) ProtoMessage() {}

func (x *PostUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserRequest.ProtoReflect.Descriptor instead.
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *PostUserRequest) GetDiscordId() int64 {
	if x != nil {
		return x.DiscordId
	}
	return 0
}

func (x *PostUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type AlterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscordId     *int64                 `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3,oneof" json:"discord_id,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterUserRequest) Reset() {
	*x = AlterUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterUserRequest) ProtoMessage() {}

func (x *AlterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterUserRequest.ProtoReflect.Descriptor instead.
func (*AlterUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *AlterUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlterUserRequest) GetDiscordId() int64 {
	if x != nil && x.DiscordId != nil {
		return *x.DiscordId
	}
	return 0
}

func (x *AlterUserRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_src_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_src_proto_user_proto protoreflect.FileDescriptor

const file_src_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14src/proto/user.proto\x12\x04user\"T\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03R\tdiscordId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"_\n" +
	"\x0eGetUserRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03H\x01R\tdiscordId\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_discord_id\"O\n" +
	"\x0fPostUserRequest\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x01 \x01(\x03R\tdiscordId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\"\x88\x01\n" +
	"\x10AlterUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03H\x00R\tdiscordId\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_discord_idB\r\n" +
	"\v_avatar_url\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xdb\x01\n" +
	"\vUserService\x12+\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\x12-\n" +
	"\bPostUser\x12\x15.user.PostUserRequest\x1a\n" +
	".user.User\x12/\n" +
	"\tAlterUser\x12\x16.user.AlterUserRequest\x1a\n" +
	".user.User\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseB2Z0github.com/KuramaSyu/Wersu-Rest/src/pb/user;userb\x06proto3"

var (
	file_src_proto_user_proto_rawDescOnce sync.Once
	file_src_proto_user_proto_rawDescData []byte
)

func file_src_proto_user_proto_rawDescGZIP() []byte {
	file_src_proto_user_proto_rawDescOnce.Do(func() {
		file_src_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_user_proto_rawDesc), len(file_src_proto_user_proto_rawDesc)))
	})
	return file_src_proto_user_proto_rawDescData
}

var file_src_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_proto_user_proto_goTypes = []any{
	(*User)(nil),               // 0: user.User
	(*GetUserRequest)(nil),     // 1: user.GetUserRequest
	(*PostUserRequest)(nil),    // 2: user.PostUserRequest
	(*AlterUserRequest)(nil),   // 3: user.AlterUserRequest
	(*DeleteUserRequest)(nil),  // 4: user.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 5: user.DeleteUserResponse
}
var file_src_proto_user_proto_depIdxs = []int32{
	1, // 0: user.UserService.GetUser:input_type -> user.GetUserRequest
	2, // 1: user.UserService.PostUser:input_type -> user.PostUserRequest
	3, // 2: user.UserService.AlterUser:input_type -> user.AlterUserRequest
	4, // 3: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	0, // 4: user.UserService.GetUser:output_type -> user.User
	0, // 5: user.UserService.PostUser:output_type -> user.User
	0, // 6: user.UserService.AlterUser:output_type -> user.User
	5, // 7: user.UserService.DeleteUser:output_type -> user.DeleteUserResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_user_proto_init() }
func file_src_proto_user_proto_init() {
	if File_src_proto_user_proto != nil {
		return
	}
	file_src_proto_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_src_proto_user_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_user_proto_rawDesc), len(file_src_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_user_proto_goTypes,
		DependencyIndexes: file_src_proto_user_proto_depIdxs,
		MessageInfos:      file_src_proto_user_proto_msgTypes,
	}.Build()
	File_src_proto_user_proto = out.File
	file_src_proto_user_proto_goTypes = nil
	file_src_proto_user_proto_depIdxs = nil
}
