// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: src/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User Messages
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscordId     int64                  `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Discriminator string                 `protobuf:"bytes,5,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetDiscordId() int64 {
	if x != nil {
		return x.DiscordId
	}
	return 0
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	DiscordId     *int64                 `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3,oneof" json:"discord_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetUserRequest) GetDiscordId() int64 {
	if x != nil && x.DiscordId != nil {
		return *x.DiscordId
	}
	return 0
}

type PostUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiscordId     int64                  `protobuf:"varint,1,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Discriminator string                 `protobuf:"bytes,4,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserRequest) Reset() {
	*x = PostUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserRequest) ProtoMessage() {}

func (x *PostUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserRequest.ProtoReflect.Descriptor instead.
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *PostUserRequest) GetDiscordId() int64 {
	if x != nil {
		return x.DiscordId
	}
	return 0
}

func (x *PostUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PostUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PostUserRequest) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *PostUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AlterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscordId     *int64                 `protobuf:"varint,2,opt,name=discord_id,json=discordId,proto3,oneof" json:"discord_id,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Username      *string                `protobuf:"bytes,4,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Discriminator *string                `protobuf:"bytes,5,opt,name=discriminator,proto3,oneof" json:"discriminator,omitempty"`
	Email         *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterUserRequest) Reset() {
	*x = AlterUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterUserRequest) ProtoMessage() {}

func (x *AlterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterUserRequest.ProtoReflect.Descriptor instead.
func (*AlterUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *AlterUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlterUserRequest) GetDiscordId() int64 {
	if x != nil && x.DiscordId != nil {
		return *x.DiscordId
	}
	return 0
}

func (x *AlterUserRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *AlterUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *AlterUserRequest) GetDiscriminator() string {
	if x != nil && x.Discriminator != nil {
		return *x.Discriminator
	}
	return ""
}

func (x *AlterUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_src_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_src_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_src_proto_user_proto protoreflect.FileDescriptor

const file_src_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14src/proto/user.proto\x12\x05proto\"\xa5\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03R\tdiscordId\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12$\n" +
	"\rdiscriminator\x18\x05 \x01(\tR\rdiscriminator\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"_\n" +
	"\x0eGetUserRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03H\x01R\tdiscordId\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_discord_id\"\xa0\x01\n" +
	"\x0fPostUserRequest\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x01 \x01(\x03R\tdiscordId\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12$\n" +
	"\rdiscriminator\x18\x04 \x01(\tR\rdiscriminator\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x8d\x02\n" +
	"\x10AlterUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\n" +
	"discord_id\x18\x02 \x01(\x03H\x00R\tdiscordId\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x04 \x01(\tH\x02R\busername\x88\x01\x01\x12)\n" +
	"\rdiscriminator\x18\x05 \x01(\tH\x03R\rdiscriminator\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x04R\x05email\x88\x01\x01B\r\n" +
	"\v_discord_idB\t\n" +
	"\a_avatarB\v\n" +
	"\t_usernameB\x10\n" +
	"\x0e_discriminatorB\b\n" +
	"\x06_email\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe3\x01\n" +
	"\vUserService\x12-\n" +
	"\aGetUser\x12\x15.proto.GetUserRequest\x1a\v.proto.User\x12/\n" +
	"\bPostUser\x12\x16.proto.PostUserRequest\x1a\v.proto.User\x121\n" +
	"\tAlterUser\x12\x17.proto.AlterUserRequest\x1a\v.proto.User\x12A\n" +
	"\n" +
	"DeleteUser\x12\x18.proto.DeleteUserRequest\x1a\x19.proto.DeleteUserResponseB1Z/github.com/KuramaSyu/WerSu-Rest/src/proto;protob\x06proto3"

var (
	file_src_proto_user_proto_rawDescOnce sync.Once
	file_src_proto_user_proto_rawDescData []byte
)

func file_src_proto_user_proto_rawDescGZIP() []byte {
	file_src_proto_user_proto_rawDescOnce.Do(func() {
		file_src_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_user_proto_rawDesc), len(file_src_proto_user_proto_rawDesc)))
	})
	return file_src_proto_user_proto_rawDescData
}

var file_src_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_src_proto_user_proto_goTypes = []any{
	(*User)(nil),               // 0: proto.User
	(*GetUserRequest)(nil),     // 1: proto.GetUserRequest
	(*PostUserRequest)(nil),    // 2: proto.PostUserRequest
	(*AlterUserRequest)(nil),   // 3: proto.AlterUserRequest
	(*DeleteUserRequest)(nil),  // 4: proto.DeleteUserRequest
	(*DeleteUserResponse)(nil), // 5: proto.DeleteUserResponse
}
var file_src_proto_user_proto_depIdxs = []int32{
	1, // 0: proto.UserService.GetUser:input_type -> proto.GetUserRequest
	2, // 1: proto.UserService.PostUser:input_type -> proto.PostUserRequest
	3, // 2: proto.UserService.AlterUser:input_type -> proto.AlterUserRequest
	4, // 3: proto.UserService.DeleteUser:input_type -> proto.DeleteUserRequest
	0, // 4: proto.UserService.GetUser:output_type -> proto.User
	0, // 5: proto.UserService.PostUser:output_type -> proto.User
	0, // 6: proto.UserService.AlterUser:output_type -> proto.User
	5, // 7: proto.UserService.DeleteUser:output_type -> proto.DeleteUserResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_user_proto_init() }
func file_src_proto_user_proto_init() {
	if File_src_proto_user_proto != nil {
		return
	}
	file_src_proto_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_src_proto_user_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_user_proto_rawDesc), len(file_src_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_user_proto_goTypes,
		DependencyIndexes: file_src_proto_user_proto_depIdxs,
		MessageInfos:      file_src_proto_user_proto_msgTypes,
	}.Build()
	File_src_proto_user_proto = out.File
	file_src_proto_user_proto_goTypes = nil
	file_src_proto_user_proto_depIdxs = nil
}
